### ISSUE TITLE
Housing Price Prediction

### ISSUE THREAD

**Issue by Santhosh-Siddhardha** [recodehive/machine-learning-repos#1]
The Housing Price Prediction model is a machine learning tool designed to predict the prices of houses based on various features such as location, size, number of rooms, and other relevant attributes. This model leverages advanced statistical techniques and machine learning algorithms to provide accurate and reliable price predictions.

Please assign me this issue, So that i can work on it

**Comment by sanjay-kv** [comment]
Make sure you create seperate folder and add the same

**Comment by itssiddhantjain** [comment]
Hello @sanjay-kv , please assign this issue to me as I have already worked on this kind of problem in the past.
