### ISSUE TITLE
💡[Feature]: Data analysis and prediction ml modal for Plant Growth

### ISSUE THREAD

**Issue by hafsa-wasi** [recodehive/machine-learning-repos#1001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Goal is to predict the growth stage or milestone that a plant reaches based on variables such as soil type, sunlight hours, water frequency, fertilizer type, temperature, and humidity. 
Data analysis of plant growth based different environmental and managemental factors. 

### Use Case

Dataset: https://www.kaggle.com/datasets/gorororororo23/plant-growth-data-classification

### Benefits

This prediction can help in understanding how different conditions influence plant growth and can be valuable for optimizing agricultural practices or greenhouse management.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
you have reached max contribution to this repo when you merge this.
