### ISSUE TITLE
Postman Challenge points not assigned

### ISSUE THREAD

**Issue by YashMall** [recodehive/machine-learning-repos#1053]
@SakshamShandilya @sanjay-kv Day before Yesterday, it was showing 500 points and since yesterday it's showing 0. My PR is https://github.com/GSSoC24/Postman-Challenge/pull/365. Still it is showing 0 in the Leaderboard.

Kindly see to it. Please!

**Comment by YashMall** [comment]
Please assign points , it's not been added for raising an issue or closing it?!

**Comment by sanjay-kv** [comment]
![image](https://github.com/user-attachments/assets/ca5f2152-c481-4f2d-af98-1cd37deffcde)
