### ISSUE TITLE
💡[Feature]:Add Breast Cancer Detection:

### ISSUE THREAD

**Issue by Anshika14528** [recodehive/machine-learning-repos#1070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Want to Add Breast Cancer Detection model which helps to detect if a person has breast cancer or not. The goal of this project is to build an ML model that can accurately classify whether a tumor is benign or malignant based on various features such as texture, perimeter, and compactness.

### Use Case

To detect Breast Cancer.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
This is already there in this repo
