### ISSUE TITLE
Change this stat on the repo

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/machine-learning-repos#1082]
![image](https://github.com/user-attachments/assets/b9fee210-d93a-4c22-aee8-0ebcf8bb0429)

**Comment by KanishkChhajed** [comment]
Hello @sanjay-kv, I am interested in this issue, can you assign it to me?

**Comment by KanishkChhajed** [comment]
Hello @sanjay-kv, I just create pull request related to this issue. Please check that request and let me know if there are any updates needed.
