### ISSUE TITLE
💡[Feature]: Gold price prediction using Lasso regression 

### ISSUE THREAD

**Issue by harinisayani** [recodehive/machine-learning-repos#1087]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add gold price prediction using machine learning algorithm.

### Use Case

This can be used to predict the gold rates using lasso regression.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by misskiran** [comment]
I also want to work on this regression model . Please assign this to me too.
