### ISSUE TITLE
💡[Feature]: Indian Currency Detection using DL

### ISSUE THREAD

**Issue by Aditijainnn** [recodehive/machine-learning-repos#1091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Creating an Indian currency detection system using deep learning involves several steps, including data collection, preprocessing, model selection, training, and evaluation. Below is a detailed overview of how to build such a system

### Use Case

The goal is to build a deep learning model that can accurately identify and classify Indian currency notes.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
dont work with anything related to currency, github will ban you
