### ISSUE TITLE
💡[Feature]:  Customer Segmentation Analysis

### ISSUE THREAD

**Issue by avii-07** [recodehive/machine-learning-repos#1094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will be analyzing the shopping behaviour of the customers based on demographic characteristics.

### Use Case

It can be used to produce a better strategy for marketing.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by singhabhinendra** [comment]
hello ,I want to contribute in this project .Can you assign me ?
@sanjay-kv
