### ISSUE TITLE
💡[Feature]: WCE Curated Colon Disease Detection

### ISSUE THREAD

**Issue by revanth1718** [recodehive/machine-learning-repos#1097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

- **Wireless Capsule Endoscopy (WCE):** WCE is a non-invasive diagnostic tool where the patient swallows a small, pill-sized camera that captures images as it travels through the gastrointestinal (GI) tract. These images are then analyzed to identify abnormalities, such as polyps or signs of diseases like colorectal cancer.

- **Curated Dataset:** The term "curated" suggests that the data used for the detection system has been carefully selected and labeled by experts. This dataset is essential for training and testing machine learning models to ensure accurate and reliable disease detection.

- **Machine Learning-Based Detection:** The project likely involves using advanced machine learning or deep learning techniques to analyze the WCE images. These models are trained to detect specific patterns or anomalies in the images, enabling early diagnosis of colon diseases, which is crucial for effective treatment and management.

I want to work on this issue 
@sanjay-kv assign me this issue under GSSOC'24

### Use Case

NA

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
https://github.com/recodehive/Stackoverflow-Analysis/issues/361

https://github.com/recodehive/Scrape-ML/issues/228

can you also look into it @revanth1718
