### ISSUE TITLE
Cat vs Dog image Classification:

### ISSUE THREAD

**Issue by Anshika14528** [recodehive/machine-learning-repos#11]
The objective is to classify images as either  a cat or a dog using various machine learning and deep learning techniques.

I agree to follow this project's Code of Conduct
I'm a GSSoC'24 contributor
I want to work on this issue

**Comment by sanjay-kv** [comment]
Make sure you create seperate folder and add the same

**Comment by lassmara** [comment]
Please assign me this issue.

**Comment by itssiddhantjain** [comment]
Hello @sanjay-kv  please assign this issue to me as I have already worked on this kind of problem in the past.

**Comment by aryanchauh** [comment]
Hello sir can you please assign me this issue?@sanjay-kv

**Comment by swati-singh23** [comment]
@sanjay-kv I request you to please assign me this issue
