### ISSUE TITLE
Customer Churn Prediction 

### ISSUE THREAD

**Issue by Mansii8224** [recodehive/machine-learning-repos#110]
Hey  , I want to create the customer churn prediction for shopping malls like Wallmart  can you please  assign this task under GSSOC ' 24 ?

**Comment by Srijansarkar17** [comment]
Hey @sanjay-kv I have worked on this issue before, so I have knowledge in this project. Can you assign it to me?

**Comment by Shouryabhardwajj** [comment]
I am interested in this issue. Please assign me this

**Comment by Mansii8224** [comment]
Thank you @sanjay-kv

**Comment by Amishachoudhary22** [comment]
I am interested in working on this issue. please assign it to me

**Comment by SayantikaLaskar** [comment]
I would like to work on this issue kindly assign me this issue
