### ISSUE TITLE
💡[Feature]: Avacado Classification

### ISSUE THREAD

**Issue by sreevidya-16** [recodehive/machine-learning-repos#1116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The project aims to predict whether an avocado is conventional or organic using Deep learning models.

🧵**DATASET**

https://www.kaggle.com/datasets/neuromusic/avocado-prices

@sanjay-kv assign me this issue under GSSOC'24

### Use Case

NA

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
![image](https://github.com/user-attachments/assets/11ca76ce-5edc-4d2e-b9a8-1ca3bd4019b2)
![image](https://github.com/user-attachments/assets/ce1cf5c2-a024-4bd9-bbce-dff76db039ab)

you have lot of spam contribution and not following the guideline + you have reached max contributions to this repo

**Comment by sreevidya-16** [comment]
@sanjay-kv, sorry sir 
I won't repeat it
Please don't consider them as spam sir 
I've done those documentations with lot of efforts
