### ISSUE TITLE
Task 29: Create a website 

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/machine-learning-repos#1133]
this is the page we are looking for 
https://codeharborhub.github.io/showcase

**Comment by shreyash3087** [comment]
@sanjay-kv what should be the framework for the website? next,react or something else?

**Comment by MastanSayyad** [comment]
> @sanjay-kv what should be the framework for the website? next,react or something else?

HTML, CSS and JS i guess

**Comment by sanjay-kv** [comment]
yes, + can use nodejs

**Comment by shreyash3087** [comment]
@sanjay-kv okay,using html,css,js with node is not a bad idea but i was just saying that using react would set it up for future upgrades as well,also using simple html in 2024,well thats a bit old practice, but okay if you want vanilla thats fine,we can go for that

**Comment by sanjay-kv** [comment]
@shreyash3087 no dont use vanilla lets go with node js

**Comment by shreyash3087** [comment]
@MastanSayyad @sanjay-kv someone has to set up a basic template for the website so that people can chose a particular section of the website and work on it then, @MastanSayyad are you gonna do it,or do you want me to do it?

**Comment by MastanSayyad** [comment]
I can create a basic template but should I also fetch the folders too if yes then which method should I use 
- Using GitHub API which is more reliable and requires API token 
- Or Using Web Scraping as no API is required

**Comment by MastanSayyad** [comment]
@shreyash3087 I think you can do it better than I can.  so you can create the template.

**Comment by shreyash3087** [comment]
@MastanSayyad i can handle the fetching part i would do it with github api, cuz it worked on helpops hub and i have some experience with it,we fetched the directories of its github repo which contained some resources using github api,the same method can work here as well.

Web scraping is also not a bad idea tho since it wont need api,we can explore both,i guess.

For the website template i guess you can add a resources page and display all the fetched machine learning resources on that particular page instead of the homepage

**Comment by MastanSayyad** [comment]
I think it would be better to display it on the homepage with pagination, as there are a lot of folders. We could also create a dedicated Organization page for RecodeHive Org.

![image](https://github.com/user-attachments/assets/8cb98daf-059b-42f8-af9c-9c6c0b60d921)

Is this template sufficient to start working on? @shreyash3087

**Comment by shreyash3087** [comment]
@MastanSayyad Yes it is sufficient

**Comment by MastanSayyad** [comment]
Alright, I'll go ahead and make a PR for this, @sanjay-kv, with a few additional changes. @shreyash3087, the fetching part is now in your hands. Let me know if you need any help!

**Comment by Saumili** [comment]
I think I am a little late to join the conversation, but I wish to contribute too

**Comment by sanjay-kv** [comment]
https://web-master-log.vercel.app/

This would be good for the main page, simple and informative.
