### ISSUE TITLE
💡[Feature]: make subcategories  folders

### ISSUE THREAD

**Issue by aditya-bhaumik** [recodehive/machine-learning-repos#1134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

@sanjay-kv  I’m not sure if this is a good idea, but I’ve noticed that there are many different classification models and prediction models in the repository. I would like to suggest that we create separate folders for each category to make the repo easier to read and navigate. Currently, there are so many folders, which makes it really hard to find what you're looking for.

Reasons for categorizing the models:

Improved Navigation: By organizing the models into distinct folders, it will be much easier for team members to find and access the specific models they need.

Better Organization: Separate folders will help maintain a cleaner and more organized structure, reducing clutter and confusion in the repository.

### Use Case

please let me know if there is anything else that i can do to or if this is a good idea 

### Benefits

If anyone would like to help me with this issue please let me know

After confirming if this issue is a good idea or not

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aditya-bhaumik** [comment]
Most of the models are either classification and prediction thats why i mentioned them if there are more subcategories please suggest them here

**Comment by sanjay-kv** [comment]
its good idea you can proceed with this
