### ISSUE TITLE
Change the Title nav @Asymtode712

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/machine-learning-repos#1141]
![image](https://github.com/user-attachments/assets/0ebde256-fb32-4a38-9e84-f2db48d3830e)
https://recodehive.github.io/awesome-github-profiles/index.html

make it similar to the above website [Ojas-Arora](https://github.com/Ojas-Arora)

**Comment by Asymtode712** [comment]
@sanjay-kv Please take a look at this:

I have changed the logo and the title text as per the given link and our current theme.... also I have fixed the github icon

![WhatsApp Image 2024-08-24 at 22 03 56_65d04d02](https://github.com/user-attachments/assets/224f11f8-d5b6-4285-bd8d-5f5142371505)

**Comment by sanjay-kv** [comment]
awesome
