### ISSUE TITLE
Change the Footer @Ojas-Arora

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/machine-learning-repos#1142]
![image](https://github.com/user-attachments/assets/6e7701a9-3d1e-462e-b5c5-c10e83b3bb3f)

https://recodehive.github.io/awesome-github-profiles/index.html

@Asymtode712

**Comment by Asymtode712** [comment]
@sanjay-kv Should I start working on it??

**Comment by sanjay-kv** [comment]
Yes

**Comment by Asymtode712** [comment]
@sanjay-kv Actually I was confused as my name as mentioned here but I'm assigned the task at #1141 .....so I'm doing that one first....

**Comment by sanjay-kv** [comment]
This is my mistake , it's assigned to ojas

**Comment by Asymtode712** [comment]
@sanjay-kv I have started working on it
