### ISSUE TITLE
add scroller @nikki-05

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/machine-learning-repos#1144]
![image](https://github.com/user-attachments/assets/5d24d8a3-101a-4619-8b30-041ad5fa9abd)

https://recodehive.github.io/awesome-github-profiles/index.html

@nikki-05

**Comment by aditya-bhaumik** [comment]
@sanjay-kv  hi i noticed that some of the issues are inactive can i help with those issues

**Comment by aslams2020** [comment]
Should I Work On this one..?

**Comment by aditya-bhaumik** [comment]
@aslams2020 you are already working on a issue right ??  finish that then take another issue

**Comment by aslams2020** [comment]
@aditya-bhaumik I started working on both.
please find other issue.

**Comment by aslams2020** [comment]
My other one is Design work, so i can work on this one too

**Comment by nikki-05** [comment]
anyone can work on it, since I'm busy with something important I cannot be active for more days as well,
sorry for any inconvenience caused by me .

**Comment by aditya-bhaumik** [comment]
yes i am working on it right now will add the pull request soon
