### ISSUE TITLE
Link code of conduct @shreya-paul-17

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/machine-learning-repos#1146]
https://recodehive.github.io/awesome-github-profiles/pages/exploremore.html#

**Comment by shreya-paul-17** [comment]
I am facing an issue regarding cloning of this repo. I have already tried thrice in a row but it is showing error regarding network connection and failing to clone completely. Can you suggest me what should I do now?

**Comment by aditya-bhaumik** [comment]
@shreya-paul-17 yes many faced that issue and were talking about in whatsapp 

vansh used github codespaces it worked 

or there are some codes are mentioned in whatsapp you can try those

**Comment by shreya-paul-17** [comment]
Ok @aditya-bhaumik , I will try. Thanks for trying to help me out
