### ISSUE TITLE
add bot like this @vansh-codes

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/machine-learning-repos#1152]
![image](https://github.com/user-attachments/assets/3e774dee-3963-4c94-be21-945a1f58680f)

@vansh-codes/

https://web-master-log.vercel.app/

**Comment by vansh-codes** [comment]
Hii @sanjay-kv 
The bot reference you shared is just a dummy bot, it doesnt do anything..
you want this dummy bot??

**Comment by sanjay-kv** [comment]
Maybe we can implement something easy. So people can type and get some info about the existing projects? 

If it's hard we will just create a dummy profile?

**Comment by vansh-codes** [comment]
We can hardcode some basic questions and answers related to the project, what do you think on this?

Real chatbot can be integrated using https://cloud.google.com/dialogflow
but its not free and also a bit complex task

**Comment by sanjay-kv** [comment]
That works

**Comment by sanjay-kv** [comment]
Don't do complicated we can hardcode

**Comment by vansh-codes** [comment]
Sure! Hardcoding few basic questions!
