### ISSUE TITLE
💡[Feature]: Integration of MongoDB for Contact Form

### ISSUE THREAD

**Issue by shreyash3087** [recodehive/machine-learning-repos#1212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

We can maybe integrate the site with mongodb and store the data from the contact form in mongodb.

### Use Case

This feature would allow the contact form to be functional and would be a great enhancement to the site

### Benefits

Allow better user experience and enhance the functionality of the webpage

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shreyash3087** [comment]
@sanjay-kv ik the contribution period is over, but i think we should work on this, atleast this would make the form functional. If you have any other plans for the DB, thats fine then otherwise i think mongo is not a bad option.

**Comment by sanjay-kv** [comment]
@shreyash3087 can we make the website link public. ? you can paste the link to me here. i will add on the info page
