### ISSUE TITLE
💡[Feature]: Super Resolution GAN (SRGAN)

### ISSUE THREAD

**Issue by ananyakaligal** [recodehive/machine-learning-repos#1223]
### Feature Description

Under the Algorithms directory, I want to implement an Image Super Resolution Enhancement feature using SRGAN to upscale low-resolution images while preserving and enhancing details for improved visual quality across various applications.

### Use Case

Image restoration, medical imaging enhancement, satellite image resolution improvement, video enhancement, face recognition accuracy improvement, gaming texture upscaling, e-commerce product image enhancement, AR/VR visual quality improvement, artwork upscaling, and data augmentation for machine learning.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by sanjay-kv** [comment]
@ananyakaligal assigned to you

**Comment by ananyakaligal** [comment]
@sanjay-kv Could you please label this as level-2 this was a pretty hard task

**Comment by sanjay-kv** [comment]
https://github.com/recodehive/machine-learning-repos/pull/1230

i already labelled level 3 in the pr
