### ISSUE TITLE
💡[Feature]: Handwritten Digit Recognition Using SVM.

### ISSUE THREAD

**Issue by srii5477** [recodehive/machine-learning-repos#1231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add a project that predicts handwritten digits using SVM.

### Use Case

Predicting handwritten digits has real-world applications and helps automating manual tasks with accuracy.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
its already there, try bringing something real time implementation

**Comment by srii5477** [comment]
Please check the updated project idea

**Comment by Teja-m9** [comment]
Hey @sanjay-kv please assign this issue to me as i have some experienece in doing these projects

**Comment by srii5477** [comment]
This issue has already been assigned to me and I have started working on it.
