### ISSUE TITLE
💡[Feature]: Add a new project (Real-Time Google Play Store Data Analytics Dashboard - Python) in Data Analysis Repo

### ISSUE THREAD

**Issue by sanyadureja** [recodehive/machine-learning-repos#1241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to contribute a feature that adds a real-time data analytics dashboard for Google Play Store apps using Python and Plotly. The dashboard is built using datasets that analyze app ratings, reviews, and downloads, providing interactive visualizations.

### Use Case

This feature will allow users to explore and analyze Google Play Store app trends through an interactive dashboard. It offers visual insights into app performance, user sentiment, and download statistics, aiding in data-driven decision-making.

### Benefits

- Adds a dynamic dashboard for visualizing app data.
- Enhances the repository's data analytics capabilities with Plotly.
- Provides an intuitive tool for users to explore app trends and make market decisions.

### Add ScreenShots

<img width="1292" alt="Screenshot 2024-10-04 at 4 28 34 PM" src="https://github.com/user-attachments/assets/83f827a3-8423-486e-81f6-812411ce1ca3">

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanyadureja** [comment]
@sanjay-kv If you find this idea suitable, please assign it to me as part of GSSoC'24 Extended with all the appropriate labels. As a beginner in open-source contributions, this would be a fantastic opportunity for me. I look forward to your response.

Thank you!

**Comment by sanyadureja** [comment]
@sanjay-kv thank you for assigning, working on it.

**Comment by prisha-sh** [comment]
Hi, I am interested in working on this project, please assign me, and I'll share my solution as soon as you ping me !!

**Comment by sanyadureja** [comment]
@prisha-sh I've already been assigned with this project by @sanjay-kv this morning and am about to create my pull request.

You can try raising another issue, thank you.

**Comment by sanyadureja** [comment]
@sanjay-kv  I've completed the task #1248  - fixed https://github.com/recodehive/machine-learning-repos/issues/1241 issue by adding the new project. Looking forward to getting my PR accepted and the project merged. Please give your meaningful suggestions.

Thank you !!

**Comment by sanjay-kv** [comment]
Awesome. I can see you have recieved couple of badge on your profile, make sure to be vocal about it on linkedin.

**Comment by sanyadureja** [comment]
> Awesome. I can see you have recieved couple of badge on your profile, make sure to be vocal about it on linkedin.

Sure @sanjay-kv I'll surely post in a couple of days.
Thanks you so much for being so supportive.

**Comment by sanyadureja** [comment]
@sanjay-kv for this project I'm unable to see the "waiting" thing on Hacktoberfest, it's showing not participating.

Please check the labels once. Refer to the ss attached here. Looking forward to your response.

Thank you!!
![Screenshot_20241006_124309_Chrome](https://github.com/user-attachments/assets/66e76752-5d93-406c-af73-1cb8894ad0c7)
