### ISSUE TITLE
Change Twitter Symbol to X in Side icon section 

### ISSUE THREAD

**Issue by Amanjayswal500** [recodehive/machine-learning-repos#1243]
I would like to propose a change to update the Twitter symbol to "X" to reflect Twitter's recent rebranding. This change ensures consistency with the platform's new identity and avoids any potential confusion for users.
 please assign this issue to me
![Screenshot 2024-10-05 102252](https://github.com/user-attachments/assets/e6290d50-96bb-4ff8-abb3-130feef3b526)

**Comment by Amanjayswal500** [comment]
@sanjay-kv please assign this to me

**Comment by TalhaPirzada** [comment]
@sanjay-kv  please assign to me
