### ISSUE TITLE
🐞[Bug]: I want to work on Code of Conduct

### ISSUE THREAD

**Issue by subin-shk** [recodehive/machine-learning-repos#1264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is no View Code of Conduct page.

### Expected behavior

The Code of Conduct page should be loaded upon clicking "View Code of Conduct" button at the footer.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/9c688623-a38c-47dd-8cd6-eaf8be742d6b)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by subin-shk** [comment]
i am unable to clone the repository. i tried both http and ssh but i could not clone it. please assign this issue to someone else. thank you.

**Comment by fah-04** [comment]
can you assign this issue to me? let me try my best
