### ISSUE TITLE
💡[Feature]Styled Cursor Pointer

### ISSUE THREAD

**Issue by CodeMosaic7** [recodehive/machine-learning-repos#1271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I propose adding a styled cursor pointer feature to enhance the user interface of the project. 

### Use Case

This feature would improve user interaction visually.

### Benefits

Implementing this feature would:

Enhance the overall aesthetic appeal of the website.
Provide immediate visual feedback, making it easier for users to identify interactive elements.
Increase user satisfaction by creating a more dynamic and responsive interface.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
No this is not a feature addition we looking for
