### ISSUE TITLE
💡[Feature]: For Stock price prediction we can use GRU model for more accuracy

### ISSUE THREAD

**Issue by chiranjeevic13** [recodehive/machine-learning-repos#1280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![Screenshot 2024-10-07 163046](https://github.com/user-attachments/assets/a8df2744-f2d4-423b-ad09-95209fc26dc1)

### Use Case

Compare to other models that used in your project , GRU will give more accuracy

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
its already there
