### ISSUE TITLE
🐞[Bug]: ADD GSSOC ext 24 and HACKTOBERFEST

### ISSUE THREAD

**Issue by alo7lika** [recodehive/machine-learning-repos#1281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Add labels for the repository to participate in hacktoberfest(Your PR/MR was submitted to a repository that is not participating in Hacktoberfest. Maintainers need to add the hacktoberfest topic to the repository, or add the hacktoberfest-accepted label to your PR/MR.)

### Expected behavior

PR would be counted on the hacktoberfest site

### Add ScreenShots

![Screenshot 2024-10-07 164033](https://github.com/user-attachments/assets/6d25c230-49bc-43c4-8632-f0a31b61227a)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by alo7lika** [comment]
![Screenshot 2024-10-07 164033](https://github.com/user-attachments/assets/6d25c230-49bc-43c4-8632-f0a31b61227a)

**Comment by sanjay-kv** [comment]
added
