### ISSUE TITLE
Sentiment Analysis of IMDB Movie Reviews

### ISSUE THREAD

**Issue by Nikitakandwal** [recodehive/machine-learning-repos#129]
Hi. I wanted to develop a sentiment analysis model, implementing various classification models to predict the number of positive and negative reviews based on sentiment in the IMDB movie dataset.

**Comment by Samik123Mit** [comment]
pls assign me the issue,i will make sure the task is done,I have prior experience with the model too.

**Comment by Nikitakandwal** [comment]
[sanjay-kv](https://github.com/sanjay-kv) 
Hi! Can you kindly add a level to this issue.
