### ISSUE TITLE
ADD-Contributing.MD

### ISSUE THREAD

**Issue by saikrishna823** [recodehive/machine-learning-repos#13]
I would like to add contributing.md file to this repository,so anyone who want to contribute can  get understand.

**Comment by saikrishna823** [comment]
Please assign this issue to me.

**Comment by saikrishna823** [comment]
hey @sanjay-kv  ,I have sent PR.Kindly verify it and let me know any issues.

**Comment by itssiddhantjain** [comment]
Hello @sanjay-kv , please assign this issue to me as I have already worked on this kind of problem in the past.
