### ISSUE TITLE
💡[Feature]: In the existing project [apple-stock-predictions-lstm.ipynb] i want to add GRU model and compare LSTM and GRU Results 

### ISSUE THREAD

**Issue by deepanshubaghel** [recodehive/machine-learning-repos#1303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

To enhance the existing stock price prediction project by integrating a Gated Recurrent Unit (GRU) model alongside the existing Long Short-Term Memory (LSTM) model. This will allow for a comparative analysis of the performance of both models on the same dataset.

### Use Case

Enhanced Predictive Analysis: Integrating a GRU model into the stock price prediction project will significantly enhance predictive analysis capabilities. By comparing GRU with the existing LSTM model, users can identify which model offers better accuracy and performance for predicting stock prices based on historical data. This comparison will allow for more informed decision-making when choosing the appropriate model for similar time-series forecasting tasks

### Benefits

Integrating the GRU model will improve prediction accuracy, offer a faster and more efficient alternative to LSTM, and provide users with greater flexibility for model selection. The feature enhances the project's versatility, making it applicable to broader time-series forecasting tasks and fostering community engagement through comparative analysis.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
its already there

**Comment by deepanshubaghel** [comment]
> its already there

I noticed that the existing code [ Prediction Models/Apple Stock Price Prediction/Models/apple-stock-predictions-lstm.ipynb ] only implements the LSTM model. I believe adding the GRU model could enhance prediction performance and provide a valuable alternative, given its efficiency and effectiveness in time-series forecasting...
