### ISSUE TITLE
💡[Feature]: Keyword Extraction Feature

### ISSUE THREAD

**Issue by A-Akhil** [recodehive/machine-learning-repos#1334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This feature would automatically identify and extract key terms or phrases from a given text or document. The extracted keywords represent the most important or frequently mentioned concepts, helping to summarize or categorize the content efficiently.

### Use Case

The feature would be useful for summarizing long documents, improving search engine indexing, or highlighting key topics. For example, users can quickly identify the main ideas of a research paper, article, or legal document without reading through the entire text.

### Benefits

    Improved Efficiency: Helps in quickly understanding the main points of lengthy documents.
    Better Search Optimization: Keywords can be used for better indexing and tagging in search engines.
    Summarization: Assists users in getting a high-level overview without needing to read the full content.
    Time Saver: Useful in research, journalism, or any field where large amounts of text need to be processed quickly.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by A-Akhil** [comment]
@sanjay-kv I would like to work on this issue, kindly please assign it to me.
Please add the necessary labels, including the appropriate level

**Comment by sanjay-kv** [comment]
i assigned you @A-Akhil
