### ISSUE TITLE
🐞[Bug]: cannot see X logo

### ISSUE THREAD

**Issue by gurliv21** [recodehive/machine-learning-repos#1335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The X logo is not displayed on the website. I’ve noticed that it either doesn’t load or is missing altogether. Can I work on fixing this bug?

### Expected behavior

i want to add X logo

### Add ScreenShots

<img width="325" alt="Screenshot 2024-10-10 at 2 03 09 PM" src="https://github.com/user-attachments/assets/b4a10af2-d538-45aa-9162-20a780ec60a1">

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by gitRoHaN** [comment]
can i do this sir

**Comment by sanjay-kv** [comment]
sorry its already assigned.
