### ISSUE TITLE
Plant Disease Detection using CNN

### ISSUE THREAD

**Issue by AKSHITHA-CHILUKA** [recodehive/machine-learning-repos#134]
Develop a convolutional neural network (CNN) model to accurately detect and classify diseases in plant leaves from images, helping farmers manage crop health more effectively.

**Comment by AKSHITHA-CHILUKA** [comment]
https://github.com/Recode-Hive/machine-learning-repos/issues/134#issue-2329711607 
My PR link I am unable to fine me in leaderboard

**Comment by sanjay-kv** [comment]
i can see you have raised the PR now and I merged , give a day time it will pop up in leaderboard.
