### ISSUE TITLE
💡[Feature]: Add FAQ Page to Enhance User Experience

### ISSUE THREAD

**Issue by IkkiOcean** [recodehive/machine-learning-repos#1342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

To improve user experience and address common inquiries, I propose adding a FAQ (Frequently Asked Questions) page to our application. The FAQ page will provide users with quick answers to recurring questions, helping them navigate the platform more efficiently and reducing the need for direct support.

### Use Case

1.	Enhanced User Experience: A dedicated FAQ page will help users find solutions to common issues without having to contact support or sift through documentation, improving overall satisfaction.
2.	Reduces Support Load: By addressing common questions directly in the FAQ, we can decrease the frequency of repetitive support tickets, allowing the team to focus on more complex issues.
3.	Increases Retention: Users are more likely to stay engaged with the platform when they can find answers quickly, especially if they encounter problems during onboarding or throughout usage.
4.	SEO Benefits: A well-structured FAQ page could contribute to improved search engine visibility, as users may search for answers to specific questions related to our product.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by IkkiOcean** [comment]
Please add level 3 to it.

**Comment by IkkiOcean** [comment]
@sanjay-kv are there any specific FAQ's you want on the page?

**Comment by sanjay-kv** [comment]
atm you just create a page similar to this https://gssoc.girlscript.tech/faq
then we will add the details later.
