### ISSUE TITLE
💡[Feature]: A complete end to end RAG chatbot application using Gemini 

### ISSUE THREAD

**Issue by pranavvb03** [recodehive/machine-learning-repos#1354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Develop a Q & A RAG (Retrieval Augmented generation) chatbot on PDF document extraction using Langchain , sentence transformers and FAISS vector indexing with Gemini API that is capable of handling multiple pdf files and answering users queries using information present in pdf files. The model is deployed on Streamlit. 

**Workflow:**
 - Document Parsing: Extract text from the PDF and divide it into chunks (paragraphs or sections).
- Vector Embedding: Convert the chunks into vector embeddings using a pre-trained sentence transformer.
 - Indexing with FAISS: Store the vectorized chunks in a FAISS index for fast similarity searches.
 - User Query: Convert the user query into a vector and use FAISS to retrieve the most relevant text chunks from the document.
 - Answer Generation: Feed the retrieved chunks and the query into the Gemini API (language model) to generate a coherent answer.
 - Response: The chatbot returns the generated answer to the user.

### Use Case

 - Document Analysis: Answering questions based on large reports, research papers, or legal documents.
 - Customer Support: Assisting customers by retrieving relevant sections from manuals, FAQs, or documentation.
 - Educational Tools: Providing students with answers based on textbook content or study materials.

### Benefits

Efficient Retrieval: FAISS enables rapid retrieval of relevant information from large documents, making the chatbot responsive even with complex or long queries.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
https://github.com/recodehive/machine-learning-repos/issues/1367
