### ISSUE TITLE
💡[Feature]:  Drug Classification System using  Supervised learning

### ISSUE THREAD

**Issue by RajKhanke** [recodehive/machine-learning-repos#1375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Using various different  supervised machine Learning algorithm , i want to make a drug classification application using Streamlit and analysis on notebook using below Kaggle drug classification Dataset :
https://www.kaggle.com/datasets/lykin22/drug-data

the input features will be :
ge
Age of the Patient

Sex
Gender of the patients

BP
Blood Pressure Levels

Cholesterol
Cholesterol Levels

Na_to_K
Sodium to potassium Ration in Blood

output :

Drug
(among five possible types such as DrugA,  DrugB , DrugC , DrugY , DrugX)

Dear Sanjay KV, i am, a gssoc-2024 extended contributor. i want  to work ion this PR for gssochacktoberfest 2024. please asisgn this issue to me along with label hacktoberfest-acceptedtag and gssoc'24-extended tag.

### Use Case

Physicians can use the model to predict the most appropriate drug type for a patient based on their age, sex, blood pressure levels, cholesterol levels, and sodium-to-potassium ratio. This allows for tailored treatment plans, improving efficacy and reducing adverse reactions.

### Benefits

Personalized Medicine
Benefit: The model enables tailored drug prescriptions by analyzing individual patient characteristics like age, sex, blood pressure, cholesterol, and electrolyte balance. This leads to better treatment outcomes, as drugs can be matched to the specific needs of each patient.
2. Improved Accuracy in Drug Selection
Benefit: The model minimizes human error by systematically considering multiple health factors to predict the most suitable drug. This reduces the likelihood of incorrect prescriptions and enhances overall treatment accuracy.
3. Reduced Side Effects
Benefit: By considering key health indicators (e.g., sodium-to-potassium ratio, blood pressure), the model helps in selecting drugs that are less likely to cause adverse side effects, improving patient safety and reducing complications.

### Add ScreenShots

NA

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
its already there
