### ISSUE TITLE
💡[Feature]: Hair type classification using CNN and neural Networks

### ISSUE THREAD

**Issue by RajKhanke** [recodehive/machine-learning-repos#1376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Dataset link : https://www.kaggle.com/datasets/kavyasreeb/hair-type-dataset

classification if inputed image hair type into straight, curly ,weavy ,curly , deadlocks, krinky etc based on user inouted and CNN classification technique. i will provide a compleet analysis of ipynb file and streamlit based gui application for the same

please assign this issue to me under gssoc'24  extended and hactoberfest-accepted tag

### Use Case

This will be useful in identifying the hairtype of different user using aiml techniques

### Benefits

Smart Automation

### Add ScreenShots

NA

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
https://github.com/recodehive/machine-learning-repos/issues/1367

**Comment by abhipsa14** [comment]
I want to contribute in this.
