### ISSUE TITLE
💡[Feature]: Raisin Binary Classification using Logistic Regression and other supervised techniques

### ISSUE THREAD

**Issue by RajKhanke** [recodehive/machine-learning-repos#1377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to develop a system for resin classification (Kecimen or besni) based on various input statistical parameters like :
Area
Gives the number of pixels within the boundaries of the raisin.

MajorAxisLength
Gives the length of the main axis, which is the longest line that can be drawn on the raisin.

MinorAxisLength
Gives the length of the small axis, which is the shortest line that can be drawn on the raisin.

Eccentricity
It gives a measure of the eccentricity of the ellipse, which has the same moments as raisins.

ConvexArea
Gives the number of pixels of the smallest convex shell of the region formed by the raisin.

Extent
Gives the ratio of the region formed by the raisin to the total pixels in the bounding box.

Perimeter
It measures the environment by calculating the distance between the boundaries of the raisin and the

using different machine learning techniques and analysis based on that and insights and web application using streamlit for prediction

please assign  this issue to me under gssoc'24 and hacktoberfest'24 with tags of both

### Use Case

It will be usefulk in analysing the natural and statistical measurements of both resins (kecimen and besni)

### Benefits

It will be helpful for raisin retailers for analysis and insights and users to overcome raisin frauds

### Add ScreenShots

NA

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
https://github.com/recodehive/machine-learning-repos/issues/1367
