### ISSUE TITLE
💡[Feature]: World Wide Unicorn Startups EDA 

### ISSUE THREAD

**Issue by deepanshubaghel** [recodehive/machine-learning-repos#1379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The "World Wide Unicorn Startups EDA" feature conducts exploratory data analysis on a dataset of unicorn startups to uncover insights regarding their valuation, industry representation, and geographic distribution through visualizations and statistical summaries. Key objectives include data cleaning, segmentation by valuation, and trend analysis across different countries and industries.

### Use Case

This feature would enhance the project by providing valuable insights into the startup ecosystem, allowing users to identify trends in valuations, understand the competitive landscape across different industries and countries, and make data-driven decisions regarding investments or market entry strategies. Additionally, it offers a foundation for further analysis or model development in startup evaluation and investment strategies.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/0662b6e4-35a7-4797-9088-26a7d4562290)

![image](https://github.com/user-attachments/assets/bbe625f9-a9f5-4e95-964f-dcbc12a4b6f9)

![{03A75F62-0BB1-42F3-BB2C-F4790796F0EB}](https://github.com/user-attachments/assets/47ddc68d-dc24-49e0-9a9b-8cbbe15b4e87)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
https://github.com/recodehive/machine-learning-repos/issues/1367

**Comment by deepanshubaghel** [comment]
@sanjay-kv  is there any chances to assign if i add proper code with readme file
