### ISSUE TITLE
💡[Feature]: ADD LSTM Model in [Prediction Models/Anemia Prediction/Anemia_prediction.ipynb]

### ISSUE THREAD

**Issue by deepanshubaghel** [recodehive/machine-learning-repos#1386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Implement an LSTM model to improve anemia prediction by capturing sequential dependencies in pixel and Hb data, and compare its performance with existing models (Logistic Regression, Decision Tree, and Gradient Boosting).

### Use Case

Adding the LSTM model will enhance the project by leveraging sequential data patterns, potentially improving prediction accuracy for anemia detection. It will also provide a deeper comparison between traditional machine learning models and deep learning approaches, offering insights into which method is best suited for this dataset.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
please checkout the pin issue
