### ISSUE TITLE
💡[Feature]: Adding Number plate detectin system.

### ISSUE THREAD

**Issue by AbhijitMotekar99** [recodehive/machine-learning-repos#1395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This feature involves adding a Number Plate Detection System to the project. The system will use computer vision and Optical Character Recognition (OCR) techniques to detect, recognize, and extract text from vehicle license plates in real-time or from images.

The implementation would utilize technologies like OpenCV for image processing and Tesseract OCR for text recognition. It will be capable of detecting number plates from various angles, improving accuracy in text extraction even in challenging environments.

### Use Case

This feature will be highly beneficial for security systems, automated toll collection, parking management, and traffic monitoring. The system can capture number plate data, store it in a database, and trigger alerts for specific plates, such as blacklisted vehicles.

### Benefits

- Automation: Eliminates the need for manual intervention in vehicle monitoring systems, improving efficiency.
- Security: Enhances security by identifying and tracking vehicles.
- Time-saving: Speedy detection and recognition will significantly reduce wait times at toll booths, parking lots, or security checks.
- Scalability: The system can be integrated into various domains such as smart cities, parking management systems, and automated security systems, benefiting a wider community.

### Add ScreenShots

![number plate detection](https://github.com/user-attachments/assets/402a861a-63f1-4e35-a3dd-98a740067cc1)

![number plate detect saved](https://github.com/user-attachments/assets/fa597322-aa89-462d-8c57-c058c347cf87)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
its already there
