### ISSUE TITLE
💡[Feature] : Adding vechical classification model

### ISSUE THREAD

**Issue by AbhijitMotekar99** [recodehive/machine-learning-repos#1396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The Vehicle Classification Model will classify vehicles into various categories such as cars, trucks, motorcycles, buses, etc., using machine learning or deep learning models. This model will leverage computer vision techniques and can be implemented using convolutional neural networks (CNN) or pre-trained models like YOLO (You Only Look Once) for object detection and classification.

### Use Case

This model can be used in traffic management systems, automated toll collection, smart city infrastructure, and parking systems where identifying the type of vehicle is necessary.

### Specific Use Case

- Traffic Monitoring: Classifying vehicles on the road to better manage traffic flows.
- Parking Systems: Allowing specific parking zones for different types of vehicles (e.g., trucks, cars, bikes).
- Toll Management: Charging toll fees based on the type of vehicle, ensuring fair pricing.
- Surveillance: Identifying and tracking different types of vehicles for security purposes.

### Benefits

- Automation in Traffic Management: Real-time classification can help in optimizing traffic signal timings and reducing congestion.
- Scalability: The model can be integrated into various systems like surveillance, toll booths, and smart parking lots, improving overall efficiency.
- Cost-effective: Automated classification reduces the need for manual monitoring and management of vehicles.
- Security and Law Enforcement: The system can be combined with a number plate recognition system to enhance the ability to track and monitor suspicious vehicles.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
its already there
