### ISSUE TITLE
Add Deepfake Image Analyzer

### ISSUE THREAD

**Issue by vidurAgg22** [recodehive/machine-learning-repos#14]
I would like to add a deep fake analyzer that can detect whether an image is fake or real as part of GSSOC'24. I have already worked on this and achieved excellent results. Please assign this task to me. I have added a video to showcase how it works. It will take me approximately one hour to complete it, as I have already worked on it.

Thank you.

https://github.com/Recode-Hive/machine-learning-repos/assets/165144144/3bbfa22b-401b-43b6-97fa-a95b23dd67b0

**Comment by sanjay-kv** [comment]
Make sure to add a new folder and do the same

**Comment by aaviiothic** [comment]
hello! i am interested and would like to work on this . please assign it to me!
