### ISSUE TITLE
💡[Feature]: Deep CNN Autoencoder - Image Compression

### ISSUE THREAD

**Issue by deepanshubaghel** [recodehive/machine-learning-repos#1400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### **Flow of Autoencoder**
**Input Image -> Encoder -> Compressed Representation -> Decoder -> Reconstruct Input Image**

![{0F739216-6EFC-480F-A16E-9C80E940CC51}](https://github.com/user-attachments/assets/4f0f8166-47ba-4e3b-b059-1ac665cf59a3)

### Use Case

The image denoising feature will really improve the project by automatically cleaning up noisy images, giving you clearer visuals. This means better accuracy for tasks like classification and analysis, making the whole experience smoother and more trustworthy for users.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
https://github.com/recodehive/machine-learning-repos/issues/1367
