### ISSUE TITLE
EDA and Classification using Decision Trees and Logistic Regression

### ISSUE THREAD

**Issue by Jaya-Prakash-17** [recodehive/machine-learning-repos#141]
Hello!
As a contributor in GsSOC24

I want to improve the repository by adding  information about Exploratory Data Analysis (EDA) and Classification methods, especially Decision Trees, Logistic Regression, and other well-known classifiers. This addition will have clear explanations, useful examples, and pictures to help people understand. Classifiers like Random Forest, Support Vector Machines, and Naive Bayes can help students learn more about classification methods by being used in our lessons. The goal of these changes is to make the source better for people who are new to Data Science. and It would be very helpful if this issue was marked as Level 2, which would show that it is moderately difficult and encourage people who want to learn more to contribute.

Thank you.

**Comment by Samik123Mit** [comment]
pls assign me the issue,i will make sure the task is done,I have prior experience with the model too.
