### ISSUE TITLE
💡[Feature]: Add Pet's Image classification

### ISSUE THREAD

**Issue by yashksaini-coder** [recodehive/machine-learning-repos#1423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Simple approach is to use infamous pet's images dataset provided by google to train a CNN model, that can be used to train & classify all 36 different pet's from their images.

### Use Case

It can be used to distinguish the different pets of look like are of same breed or class. Also a visual file of the trained model.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by yashksaini-coder** [comment]
can this issue be assigned to me @sanjay-kv

**Comment by sanjay-kv** [comment]
its already there, please read pinned issuee
