### ISSUE TITLE
Time Series Analysis using ARIMA for Stock prediction

### ISSUE THREAD

**Issue by DarshAgrawal14** [recodehive/machine-learning-repos#1424]
I would like to contribute by adding a time series analysis model for stock prediction as most the models found on internet use LSTM or other regression models and do not take the day of exchange into account . This model by taking date and dividing it into day, month and year along with lags. A dataset found on internet was upgraded to support time series analysis and a ARIMA model is trained on it.

Darsh Agrawal , GSSoC 24 extd contributor

**Comment by sanjay-kv** [comment]
i have pinned issue on issue page, please read, meanwhile this is already existing
