### ISSUE TITLE
📝[Docs]: contributing.md file

### ISSUE THREAD

**Issue by INam1995** [recodehive/machine-learning-repos#1427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

This file will provide clear guidelines for potential contributors, enhancing our community's onboarding experience and encouraging more participation.

### Suggested Change

Here’s a brief overview of what I plan to include in the CONTRIBUTING.md file:

Project Overview
Getting Started instructions
Contributing Guidelines
Implementation steps for the search functionality enhancement
Acknowledgment of the project's Code of Conduct

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
[contributerGuidelines.md](https://github.com/recodehive/machine-learning-repos/blob/main/contributerGuidelines.md)

there is already one
