### ISSUE TITLE
💡[Feature]: Button Styling Needs Update to Match Website Theme

### ISSUE THREAD

**Issue by neeru24** [recodehive/machine-learning-repos#1431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The current button styling on the website does not align with the overall theme, leading to a visual inconsistency that affects the user experience. Updating the button styles to better reflect the website's design will enhance the aesthetic appeal and provide a more cohesive look

### Use Case

- User Interaction: Users are more likely to engage with buttons that are visually appealing and consistent with the site's design.
- Brand Identity: Consistent styling reinforces the brand's identity and improves overall user perception.

### Benefits

- Visual Consistency: Enhances the overall aesthetic.
- Improved Engagement: Encourages user interaction.
- Usability: Aids navigation and action-taking.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/2c862fb1-8fb4-4081-a513-7c432696c5b1)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by gitRoHaN** [comment]
Can I do this

**Comment by sanjay-kv** [comment]
its already assinged and merged you can see here
