### ISSUE TITLE
📝[Docs]: ADD README on FOOD ALLERGY PREDICTION MODEL (EXISTING ON THE ML-REPO)

### ISSUE THREAD

**Issue by alo7lika** [recodehive/machine-learning-repos#1446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

In the prediction folder Food allergy prediction model there is no readme present for better understanding.

### Suggested Change

To add a proper README on the project to help the audience understand the project

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by akhilesh1709** [comment]
please assign me this task
