### ISSUE TITLE
📝[Docs]: Projects under the 'Algorithms and Deep Learning Models' directory are missing README files

### ISSUE THREAD

**Issue by ananas304** [recodehive/machine-learning-repos#1452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### The following projects under the "**Algorithms and Deep Learning Models**" directory are missing README files. 
These projects require clear documentation including project descriptions, setup instructions, and any necessary files like README.md, requirements.txt(e.g., datasets, images, or demo videos):

1. [Algorithms and Deep Learning Models/QR-Scanner](https://github.com/recodehive/machine-learning-repos/tree/main/Algorithms%20and%20Deep%20Learning%20Models/QR-Scanner)
2. [Algorithms and Deep Learning Models/Boxoffice](https://github.com/recodehive/machine-learning-repos/tree/main/Algorithms%20and%20Deep%20Learning%20Models/Boxoffice) (this one is also missing a .csv file)
3. [Algorithms and Deep Learning Models/Erasing Clouds from Satellite Imagery](https://github.com/recodehive/machine-learning-repos/tree/main/Algorithms%20and%20Deep%20Learning%20Models/Erasing%20Clouds%20from%20Satellite%20Imagery)

### Suggested Change

The README files should include:

- Project title and description
- Installation and setup instructions
- Explanation of input and output files
- Dependencies and libraries used
- How to run the project (commands, scripts, etc.)
- Example images, demo video (if required), or screenshots of outputs
- For `Boxoffice`, include details about the missing .csv file and provide a sample or instructions to retrieve it.

### Rationale

Proper documentation is essential for users and contributors to understand how to use, contribute to, and interact with these projects. Including images and demo videos can enhance clarity and provide visual understanding. Additionally, providing missing datasets like the `.csv` file for `Boxoffice` will allow the project to be functional.

- Please add the following tags to the issue: `gssoc`, `gssoc-ext`, `hacktoberfest`.
- Kindly assign this issue to @ananas304.

Thankyou for your time :)

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Niraj1608** [comment]
@sanjay-kv assign me
