### ISSUE TITLE
💡[Feature]: Enhance and merge email spam detection notebook with EDA and NLP improvements

### ISSUE THREAD

**Issue by Niraj1608** [recodehive/machine-learning-repos#1455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hi, I am Niraj. I've been reviewing the Email Spam Detection with Machine Learning project and noticed several areas where improvements can be made. Specifically, I propose:

**Enhanced EDA**: Adding more detailed charts and visualizations using Python libraries like Seaborn or Matplotlib will help in better understanding the data distribution and correlation between features. This could include heatmaps, pair plots, and distribution plots to visualize relationships and patterns in the data.
**Advanced NLP Techniques**: Incorporating more Natural Language Processing (NLP) techniques, such as advanced tokenization, lemmatization, and more sophisticated vectorization techniques like TF-IDF.
**Data Cleaning:** Introducing robust data cleaning methods to remove noisy data, handle missing values, and preprocess text data more efficiently will improve the model's accuracy.
This would enhance the overall performance of the spam detection model by making it more interpretable and efficient through better visualizations and data processing.
**Dataset Issue:** The project is missing the dataset required for running the notebook. I propose including a well-structured dataset to ensure reproducibility and ease of use for others.

If you like this idea, please assign this task to me, and I will add the corresponding improvements and charts to it.

Thank you for your time and consideration!

### Use Case

Incorporating the enhanced EDA and advanced NLP techniques from the Spam Mail Predictor notebook will provide better insights into the dataset, leading to more accurate model training and predictions. This is crucial for users looking for deeper analysis and improved model performance.

### Benefits

Improved EDA: The Spam Mail Predictor notebook features more detailed EDA, including additional visualizations and insights.
Enhanced NLP: It also includes more advanced NLP techniques, such as TF-IDF and more extensive text preprocessing steps.
Dataset Integration: Adding a clear, usable dataset to the notebook will ensure reproducibility and ease of use for others.

### Add ScreenShots

@sanjay-kv once you assign me work i will create it .

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Niraj1608** [comment]
@sanjay-kv 
I understand your point, but I believe the current implementation lacks the advanced NLP techniques that could significantly improve the model's accuracy and text processing. By incorporating features like TF-IDF and advanced tokenization, we can enhance the spam detection’s robustness and efficiency. I've also added my code file as a PDF for reference
[spam_mail_pridector.ipynb - Colab.pdf](https://github.com/user-attachments/files/17390321/spam_mail_pridector.ipynb.-.Colab.pdf)

**Comment by Niraj1608** [comment]
@sanjay-kv Can it be alright to either replace an existing file with this or add it to the current one? Let me know what you prefer!

**Comment by sanjay-kv** [comment]
add it to the current one

**Comment by Niraj1608** [comment]
@sanjay-kv its level 2 issue and merged pr but got 10 points can you check pls :)

**Comment by sanjay-kv** [comment]
share ss

**Comment by Niraj1608** [comment]
![Screenshot 2024-10-16 205631](https://github.com/user-attachments/assets/d81b9109-082b-433c-97bf-2db516281ce6)
#1459

**Comment by sanjay-kv** [comment]
![image](https://github.com/user-attachments/assets/77b5f550-3d65-4e64-bf25-cfc210070674)

**Comment by sanjay-kv** [comment]
updated
