### ISSUE TITLE
🐞[Bug]: Links in header don't redirect to any thing

### ISSUE THREAD

**Issue by JomanaMahmoud** [recodehive/machine-learning-repos#1465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The links in the header section of the website, such as 'About' and 'FAQ', are not redirecting to their respective pages when clicked. This issue causes confusion for users trying to navigate the website.

### Expected behavior

Should redirect the user to the page clicked on. I would like to fix this by ensuring the links are correctly mapped to their corresponding pages and functioning as expected.

Please assign this issue to me under the GSSoC and Hacktoberfest-accepted labels.

### Add ScreenShots

https://github.com/user-attachments/assets/2fc01f2a-b1b9-4a8d-899a-878bab45a813

### What browsers are you seeing the problem on?

Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by gitRoHaN** [comment]
Can i do this?

**Comment by JomanaMahmoud** [comment]
is there a specific page i should redirect to from 'how-we-work' and 'projects' and 'team' or they not yet implemented? i redirected the projects to the model.html page is this it's correct purpose? Please keep my updated so that i can change it in the code as well @sanjay-kv

**Comment by sanjay-kv** [comment]
you can redirect to here: https://github.com/recodehive

**Comment by JomanaMahmoud** [comment]
All of the pages "how-we-work" and "team" and "projects"?
