### ISSUE TITLE
💡[Feature]: Want to add Ball Tracking opencv

### ISSUE THREAD

**Issue by Mansi07sharma** [recodehive/machine-learning-repos#1469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

A ball is tracked by opencv library

Kindly assign me this issue @sanjay-kv 

### Use Case

To detect objects

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
check the pinned issues.
