### ISSUE TITLE
Bridge Load Capacity using ML prediction

### ISSUE THREAD

**Issue by princejaiswal19** [recodehive/machine-learning-repos#147]
Nowadays a large number of bridges collapses due to lack of maintenance which takes the life of many people. Thus a ML model which predict the where the bridge is safe or not based on the load.

**Comment by princejaiswal19** [comment]
@sanjay-kv  Sir Can You assign me to work on this under GSSOC'24

**Comment by Samik123Mit** [comment]
pls assign me the issue,i will make sure the task is done,I have prior experience with the model too.
