### ISSUE TITLE
💡[Uniform Theme]: Redesign the website

### ISSUE THREAD

**Issue by dev129** [recodehive/machine-learning-repos#1472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

**Uniform Format Implementation:** Introduce a standardized design and layout across all pages of the website to enhance user experience, accessibility, and brand consistency.

### Use Case

1. **User Experience:** Users navigating the website will benefit from a cohesive design that reduces confusion and enhances engagement. For instance, a consistent color scheme and typography can make information easier to digest.
   
2. **Development Efficiency:** A defined format allows developers to create new pages and features more quickly, as they can rely on established templates rather than starting from scratch.

3. **Accessibility:** A uniform format can be designed to meet accessibility standards, ensuring that all users, including those with disabilities, have a seamless experience.

### Benefits

- **Increased User Retention:** A well-structured website encourages visitors to stay longer, reducing bounce rates and increasing conversions.
- **Brand Identity Strengthening:** Consistency in design reinforces brand recognition and trust.
- **Easier Maintenance:** Future updates and maintenance will be simplified with a standardized format, allowing for quicker rollouts of changes.
- **Community Engagement:** A cohesive platform invites more contributions from the community, as users feel more comfortable navigating and participating.

Assigning with Hacktoberfest, Level 3, and GSSoC-EXT label will not only elevate the project but also showcase the organization’s commitment to quality and innovation.

After assigning me, the wireframe shall be shared in within 2 hours and the new design shall be present within the next 48 hours.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by dev129** [comment]
Are you up @mehul-m-prajapati @sanjay-kv @somaiaahmed @Garvanand ? Anyone ?

**Comment by mehul-m-prajapati** [comment]
Yes @dev129 . Can you describe what exactly you need in this one ?

**Comment by mehul-m-prajapati** [comment]
Yes @dev129 . I think we should breakdown these requirements and create separate issues

**Comment by dev129** [comment]
So @mehul-m-prajapati do you want to say I should close this issue and create a new issue ?

**Comment by mehul-m-prajapati** [comment]
Yeah, the description is way too long. You should divide these into smaller tasks

**Comment by Garvanand** [comment]
Yes @dev129 . we can breakdown these requirements as it would be a better idea

**Comment by dev129** [comment]
So what should
