### ISSUE TITLE
💡[Feature]: New Project - Fake News Detection

### ISSUE THREAD

**Issue by PrAyAg9** [recodehive/machine-learning-repos#1483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I am integrating this machine learning project under the category of classification models

### Use Case

Used for detecting fake news.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Panchadip-128** [comment]
Hi, Can i be assigned this task?

**Comment by PrAyAg9** [comment]
@sanjay-kv Could you please add the labels and assign this pr to me, You did it in Issue but i suppose you forgot to add it here?
