### ISSUE TITLE
📝[Docs]: add ML books in the books section

### ISSUE THREAD

**Issue by Anu142004** [recodehive/machine-learning-repos#1485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

The readme file needed to be updated 

### Suggested Change

add some ML books for beginners such as:
1. "Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow" by Aurélien Géron
2. "Machine Learning Yearning" by Andrew Ng
3. "Python Machine Learning" by Sebastian Raschka and Vahid Mirjalili
4. "Introduction to Machine Learning with Python" by Andreas C. Müller and Sarah Guido
5. "Pattern Recognition and Machine Learning" by Christopher M. Bishop
6. "The Hundred-Page Machine Learning Book" by Andriy Burkov
7. "Deep Learning" by Ian Goodfellow, Yoshua Bengio, and Aaron Courville
8. "Data Science for Business" by Foster Provost and Tom Fawcett
9."Machine Learning for Absolute Beginners" by Oliver Theobald

### Rationale

yes it is necessary for understanding the project 

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Anu142004** [comment]
please do add hacktoberfest tag

**Comment by coderhetal** [comment]
Pleaseassign me to this , I have few books to add to this .
