### ISSUE TITLE
💡[Feature]: Heart Disease Prediction Model

### ISSUE THREAD

**Issue by MJakash** [recodehive/machine-learning-repos#1497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Using the required dataset, Model is trained to predict whether a persion is suffering from heart disease or not.

### Use Case

The use case of this project, where a model is trained to predict whether a person is suffering from heart disease or not, can have significant real-world applications in the healthcare sector.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by MJakash** [comment]
@sanjay-kv can you please assign me this issue and add tag hacktoberfest to it ?

**Comment by sanjay-kv** [comment]
its already there
