### ISSUE TITLE
💡[Feature]: Creating a LLM Advanced Copilot Extension for VS Code IDE

### ISSUE THREAD

**Issue by Panchadip-128** [recodehive/machine-learning-repos#1502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This extension was developed to enhance coding efficiency by integrating advanced language models like Llama 3.1, OpenAI’s GPT-3.5-turbo, and Gemini 1.5. These models offer powerful code generation, suggestion capabilities, and the ability to solve complex coding problems. The extension is designed with a user-friendly interface and can be easily integrated into your existing workflow.

### Use Case

Powerful Coding assistant
Debugs code efficiently with the help of advanced LLMs 
Gives Code suggestions
Improves user experience while coding

### Benefits

A complete Coding LLM Copilot engine, build to provide a seamless coding experience from debugging code to giving suggestions to generating code , this copilot has got all aspects covered

### Add ScreenShots

![copilot2](https://github.com/user-attachments/assets/cf4490a8-3ffd-4b4c-b672-673a09346429)
![copilot1](https://github.com/user-attachments/assets/52df2c7c-a7ac-4966-884a-4a3863b50f51)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Panchadip-128** [comment]
@sanjay-kv Please review once

**Comment by sanjay-kv** [comment]
can we connect on this, i would like to discuss more opportunity on this

**Comment by Panchadip-128** [comment]
> can we connect on this, i would like to discuss more opportunity on this

Yes sir, Sure

**Comment by sanjay-kv** [comment]
https://www.linkedin.com/in/sanjay-k-v/


Please connect with me.
