### ISSUE TITLE
💡[Feature]: Add Text Summarization NLP Project to machine learning repos

### ISSUE THREAD

**Issue by sanchitc05** [recodehive/machine-learning-repos#1506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

#### Issue Description:
Hi, I would like to contribute an **NLP project** titled **Text Summarization** to this repository. This project focuses on automatically generating summaries of long documents using **Extractive Summarization**. It provides two approaches:

1. **Gensim-based Summarization**: Uses Gensim’s built-in `summarize` function to generate concise summaries by selecting the most important sentences.
2. **Custom Sentence Ranking Summarization**: Ranks sentences based on word frequency and importance to extract key sentences from the document.

#### Tech stack:
- **Python**: The entire project is implemented in Python.
- **NLTK**: For text preprocessing (tokenization, stopwords).
- **Gensim**: For extractive summarization.

#### Suggested directory:
The project could be added under a new folder titled `text-summarization`, or it can be added to an existing NLP section if available.

Please assign this issue to me, and I would be happy to contribute this project to the repository. Let me know if any further details are needed.

Thank you!

#### Features of the project:
- **Extractive Summarization**: Key sentences are selected from the input text.
- **Gensim and Custom Approaches**: Includes both Gensim's summarization method and a custom method using NLTK for tokenization, word frequencies, and sentence ranking.
- **Well-Documented Code**: Includes comments and explanations to help beginners understand the project.
- **Preprocessing with NLTK**: The text is tokenized into words and sentences, and stopwords are removed for a more efficient summarization process.

### 1. **Simplifies Information Extraction**
   - The Text Summarization feature helps users condense long documents into short, readable summaries, making it easier to grasp key points without reading the entire text. This is especially useful for processing large volumes of information, such as research papers, news articles, or reports.

### 2. **Supports Multiple Approaches**
   - By including both **Gensim-based** and **Custom Extractive Summarization** methods, this feature offers flexibility in summarizing text. Users can choose a quick, pre-built solution (Gensim) or explore how custom sentence ranking works to fine-tune summaries based on their needs.

### 3. **Real-world Use Cases**
   - The project can be applied to various fields such as:
     - **Journalism**: Quickly summarizing news articles.
     - **Education**: Condensing academic papers or textbooks.
     - **Business**: Summarizing lengthy business reports, emails, or documents.

### 4. **Improves Efficiency**
   - The feature reduces the time spent reading long documents by generating concise versions, helping users focus on the most important sections and increasing productivity.

### 5. **Teaches Key NLP Concepts**
   - This project is an excellent resource for beginners who want to learn NLP. It demonstrates key concepts like:
     - Tokenization
     - Removing stopwords
     - Sentence ranking
     - Working with libraries like NLTK and Gensim

### 6. **Extendable for Future Development**
   - The project can be extended in the future to include **Abstractive Summarization**, where new sentences are generated, or improved to handle multi-lingual text. It provides a strong foundation for further development.

### 7. **Enhances the Repository**
   - Adding this feature enhances the repository’s value by introducing a practical NLP tool, making the repo more appealing to users who are interested in Natural Language Processing and machine learning applications. It also aligns well with the goals of a machine learning repository, as it covers a key topic in the field.

These advantages make the **Text Summarization** feature a valuable addition to the repository, providing both practical benefits and learning opportunities for users.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
its already there
