### ISSUE TITLE
Laptop Price Prediction Model

### ISSUE THREAD

**Issue by MJakash** [recodehive/machine-learning-repos#1511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Using 1300+ rows and 12 features, machine learning model has been trained to help user to guess laptops price through laptop features. it consist of different machine learning models like RandomForestRegressor, XgBoost, GradientBoost etc. to predict accurately.

### Use Case

machine learning model has been trained to help user to guess laptops price through laptop features. 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by MJakash** [comment]
@sanjay-kv can you please assign me this issue and add hacktoberfest tag to it?

**Comment by sanjay-kv** [comment]
This is already existing, i would suggest you to check the pinned issue
