### ISSUE TITLE
Update navigation bar in every page 

### ISSUE THREAD

**Issue by Abankita** [recodehive/machine-learning-repos#1514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The navigation bar is not present in all the pages. Also the link to feedback is not present in the navigation bar. 

The changes I propose:
- Add navigation bar in all existing pages.
- Add feedback page link in the navigation bar.

### Use Case

This feature will help users to navigate easily without any hassle. The updated navigation bar with the feedback link will help users to provide their valuable feedback.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by gitRoHaN** [comment]
can i contribute
