### ISSUE TITLE
💡[Feature]: Add "Image classification to identify humans or horses using CNN" project 

### ISSUE THREAD

**Issue by avogadroB** [recodehive/machine-learning-repos#1540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

A project based on python to recognize whether an image is a human or a horse using CNN with an accuracy of 97.66%

### Use Case

Classifying images based on images and corresponding labels from the input file, we employed a Multi-label Convolutional Neural Network (CNN) classification algorithm. Using CNNs for it’s ability to automatically learn hierarchical features directly from raw pixel data, enabling accurate classification of constellations based on subtle visual cues.

### Benefits

This is a starter project for understanding how convolution neural networks work. Would help the community in understanding the basics of computer vision. 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
check the pinned issue
