### ISSUE TITLE
💡[Feature]: Add Computer Vision Based Snake Game under OpenCV projects folder 

### ISSUE THREAD

**Issue by sanyadureja** [recodehive/machine-learning-repos#1546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The Computer Vision-based snake game is a novel approach to the traditional game of snake, where the player controls the movement of a snake to earn rewards and grow in length while avoiding collision with obstacles or the boundaries of the game screen.

### Use Case

The Computer Vision-based Snake Game allows players to control the snake using hand gestures detected by a webcam, making gameplay more interactive and engaging.

CV libraries such as Mediapipe, OpenCV and PyGame will be used.

### Benefits

- Enhances user interaction through gesture-based control.
- Provides a fun way to explore computer vision and image processing techniques.
- Can be integrated with open-source projects to promote learning in computer vision and game development.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanyadureja** [comment]
@sanjay-kv I would request you to please assign me with this issue and assign all the necessary labels.

**Comment by sanyadureja** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> The Computer Vision-based snake game is a novel approach to the traditional game of snake, where the player controls the movement of a snake to earn rewards and grow in length while avoiding collision with obstacles or the boundaries of the game screen.
> 
> ### Use Case
> The Computer Vision-based Snake Game allows players to control the snake using hand gestures detected by a webcam, making gameplay more interactive and engaging.
> 
> CV libraries such as Mediapipe, OpenCV and PyGame will be used.
> 
> ### Benefits
> * Enhances user interaction through gesture-based control.
> * Provides a fun way to explore computer vision and image processing techniques.
> * Can be integrated with open-source projects to promote learning in computer vision and game development.
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

**Comment by sanjay-kv** [comment]
https://github.com/recodehive/machine-learning-repos/issues/1367

not accetpting new issue,. refere above

**Comment by sanyadureja** [comment]
> #1367
> 
> not accetpting new issue,. refere above

Okay @sanjay-kv
