### ISSUE TITLE
💡[Feature]:  Adding a custom preloader

### ISSUE THREAD

**Issue by Peart-Guy** [recodehive/machine-learning-repos#1567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add a custom preloader which will match the theme and aesthetic of the webapp

@sanjay-kv  Kindly assign me the work.

I have provided a sample video.  The final product may vary depending on your specific needs and preferences. I look forward to the opportunity to contribute to your project .

### Use Case

..

### Add ScreenShots

https://github.com/user-attachments/assets/ad980c1a-ed08-45e4-bef4-5dc7bba15226

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
not required
