### ISSUE TITLE
💡[Feature]: Addition of FAQ page 

### ISSUE THREAD

**Issue by Peart-Guy** [recodehive/machine-learning-repos#1570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add the FAQ page which currently does not exist in the website.

@sanjay-kv  Kindly assign me the issue.

### Use Case

I will make a new FAQ page which will match the aesthetic and theme of the website

### Benefits

FAQ page helps users to get answer of the questions which are very frequently asked.

### Add ScreenShots

I will redesign  this Page

![image](https://github.com/user-attachments/assets/f963900c-11dc-43eb-9f66-371e22eff71a)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by JOSHITHA6** [comment]
@sanjay-kv kindly assign this task to me under gssoc'24 extd and hacktoberfest.

**Comment by Peart-Guy** [comment]
@sanjay-kv  KIndly assign me the issue so I can contribute.

**Comment by Peart-Guy** [comment]
@sanjay-kv  the FAQ page already exists in the code files . Kindly update the lInk in the github page for BEtter understanding

**Comment by sanjay-kv** [comment]
i think its the deployment issues
