### ISSUE TITLE
💡[Feature]: Add Output Format Options (JSON, CSV, TXT, XML) for Extracted Keywords and Summary in NLP/textsummary.py

### ISSUE THREAD

**Issue by shreyasparaj** [recodehive/machine-learning-repos#1571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I propose adding functionality to allow users to specify the output file format for keywords and summaries. Currently, the application only supports exporting results in JSON and CSV formats. Adding options for other formats like TXT or XML would enhance usability and flexibility for users who may require different formats for their workflows.

### Use Case

This feature would be beneficial for users who work in environments where specific file formats are preferred or required. For instance, users may need to integrate the output into different systems or applications that accept only certain formats. Being able to choose the output format directly from the application would streamline the process and eliminate the need for manual conversion.

### Benefits

Implementing this feature would:

- Enhance user experience by providing more options for exporting results.
- Increase the application's flexibility and adaptability for various use cases.
- Potentially broaden the user base by catering to those who require different output formats.

### Add ScreenShots

NA

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
i didnt get this

**Comment by shreyasparaj** [comment]
@sanjay-kv updated Title details . please check
