### ISSUE TITLE
💡[Feature]: Brain Tumor Classification

### ISSUE THREAD

**Issue by MahraibFatima** [recodehive/machine-learning-repos#1580]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

**Definition:** A brain tumor is an abnormal growth of brain cells, whether in the brain tissue itself or in surrounding tissues such as the meninges or nerves associated with the brain. These tumors can be benign (non-cancerous) or malignant (cancerous).

**Severity:** The severity of a tumor depends on its size, location, and rate of growth. Since the brain is the control center for the entire body, any pressure or damage to a specific part of the brain can cause major problems in vital body functions such as movement, sensation, vision, and memory. Cancerous tumors are more dangerous because they grow quickly and spread to other areas of the brain or body.

### Use Case

This is a tumor that occurs in the pituitary gland, which is a small gland at the base of the brain that controls the body's hormones. On MRI: You will see the pituitary gland larger than normal or you may find small lumps around the gland.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
please see the pinned issue
