### ISSUE TITLE
💡[Feature]: Addition of Apple Detection and Counting Model

### ISSUE THREAD

**Issue by nishthaa-m** [recodehive/machine-learning-repos#1585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

**The Apple Detection and Counting** feature utilizes a **YOLOv8**-based object detection pipeline to identify and track apples in videos. This feature implements a centroid-based tracking algorithm that maintains unique IDs for each apple across frames, allowing for accurate tracking even when apples overlap or temporarily disappear. The detected apples are annotated with labels, and a cumulative count is displayed in real time within the output video.

### Use Case

This feature is especially beneficial for apple orchards, where farmers and agricultural managers need to monitor apple counts for yield estimation and inventory management. By automating the detection and counting of apples on trees, orchard operators can gain valuable insights into crop productivity and health, facilitating timely decisions regarding harvesting and resource allocation.

### Benefits

Implementing this feature provides several advantages:
1) Efficiency: Automates the counting and tracking process, significantly reducing the need for manual labor.
2) Accuracy: Ensures reliable apple counts even with occlusions, minimizing errors in yield assessments.
3) Real-Time Monitoring: Offers immediate insights into apple counts, aiding in effective planning and management.
4) Versatility: Can be adapted to various orchard setups, enhancing its applicability across different farming operations.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by nishthaa-m** [comment]
@sanjay-kv Please assign me this issue with necessary labels

**Comment by sanjay-kv** [comment]
kindly see the pinned issues
