### ISSUE TITLE
💡[Feature]: adding an CV model for object size detection 

### ISSUE THREAD

**Issue by Sameeratweb** [recodehive/machine-learning-repos#1601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

object size detection model involves using computer vision techniques to estimate the physical dimensions of an object in an image.

### Use Case

Object size detection helps assess the size of obstacles.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
please see pinned issue
