### ISSUE TITLE
💡[Feature]: Interactive Decision Tree generator

### ISSUE THREAD

**Issue by yashksaini-coder** [recodehive/machine-learning-repos#1606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Tech stack : HTML, Javascript, Python, Jupyter
Objective : To create an interactive HTML decision tree model
Summary : This python package allows user to create an interactive HTML decision tree

### Use Case

To create an interactive HTML decision tree graph, user can scroll and look to different features that branches off to another decisive factor

### Benefits

To allow users to interact with decision tree chart & figures interactively

### Add ScreenShots

[HTML-decision-tree.webm](https://github.com/user-attachments/assets/ced9bd28-ea0d-4697-8fa1-8947472aa150)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
see the pinned issue

**Comment by yashksaini-coder** [comment]
> see the pinned issue

should I close this and focus on the website enhancements only @sanjay-kv 
I can add a stargazers timeline video to showcase the star history in new way
