### ISSUE TITLE
 faq page 

### ISSUE THREAD

**Issue by meghanakn473** [recodehive/machine-learning-repos#1625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add content to faq page and connect ot back to home page
@sanjay-kv kindly assign me this issue

### Use Case

It helps users to know more about the project

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by meghanakn473** [comment]
@sanjay-kv please assign me this issue

**Comment by sanjay-kv** [comment]
dont work on issue if not assigned to you
