### ISSUE TITLE
Newsletter form Submission 

### ISSUE THREAD

**Issue by meghanakn473** [recodehive/machine-learning-repos#1627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add newsletter form Submission component in the footer section of the page
@sanjay-kv kindly assign me the issue

### Use Case

This feature helps users to subscribe and be updated with the events 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
I will provide you the respective code, i mean embeded one.

**Comment by meghanakn473** [comment]
@sanjay-kv  okay sure
