### ISSUE TITLE
💡[Feature]: FAQ page need to be added

### ISSUE THREAD

**Issue by likitha-kapu** [recodehive/machine-learning-repos#1628]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Feature Description

 The application currently lacks a dedicated FAQ (Frequently Asked Questions) page, which impacts user experience by making it harder for users to find answers to common questions or troubleshoot issues independently.

### Use Case

The FAQ (Frequently Asked Questions) page is a helpful feature that provides users with answers to common questions, improving their experience by quickly addressing their concerns without needing direct support. It will contain a list of categorized questions and answers related to the product, service, or platform, making it easier for users to find relevant information.

### Add ScreenShots

![Screenshot 2024-11-07 104818](https://github.com/user-attachments/assets/cd5ddb20-351e-472e-97d2-6ebbc8a48665)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by likitha-kapu** [comment]
@sanjay-kv  please assign me this task

**Comment by meghanakn473** [comment]
@likitha-kapu issue #1692 is already raised by me...please search other issue
