### ISSUE TITLE
Addition of Phishing URL Detection

### ISSUE THREAD

**Issue by shriyadindi** [recodehive/machine-learning-repos#1631]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Phishing URL Detection Model is to detect malicious URLs that are used for phishing attacks, protecting users from deceptive websites that aim to steal sensitive information.

### Suggested Change

Addition of Phishing Detection under Detection Models

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
Kindly read the pinned issue, you can add readme to existing file.
