### ISSUE TITLE
Add Iris flower Classification

### ISSUE THREAD

**Issue by vidurAgg22** [recodehive/machine-learning-repos#17]
I would like to add a project on iris flower classification as part of GSSOC'24 where I will use different models like KNN, Random Forest, and SVM. I have worked on this before, and I believe it can be completed in one day.

please assign this issue to me @sanjay-kv

**Comment by sanjay-kv** [comment]
Make sure you create seperate folder and add the same

**Comment by ldneal** [comment]
Sir I would Like to add coding the project Bcauz I have already done IRIS Classification Project If you want to see my project Can You Assign Me as a contributor.

![Screenshot (87)](https://github.com/Recode-Hive/machine-learning-repos/assets/131946106/0bf264c8-51b7-4bf5-bae6-7326f32c54eb)
