### ISSUE TITLE
Sales_Analysis

### ISSUE THREAD

**Issue by Ruchita019** [recodehive/machine-learning-repos#184]
I am GSSoC 24 contributor and I have created a Sales Analysis of an Electronics Company.
This project primarily uses python, pandas and matplotlib.
This repository is well-documented. Even the jupyter notebook have proper explanation with steps.
please assign me this issue under level 2.

**Comment by Samik123Mit** [comment]
pls assign me the issue,i will make sure the task is done,I have prior experience with the model too.
