### ISSUE TITLE
Facial Emotion Detection using OpenCV & Keras

### ISSUE THREAD

**Issue by shagun122** [recodehive/machine-learning-repos#190]
This project will help to build a strong understanding of deep learning concepts along with the hands-on practice of implementing OpenCV, Keras and Tensorflow for projects that may be associated with these concepts.

**Comment by shagun122** [comment]
@sanjay-kv Please assign this issue to me.

**Comment by Dhwanika26** [comment]
@sanjay-kv please assign this issue to me .I have done similar work before
