### ISSUE TITLE
New Project Addition: Brain Tumor Detection with Web App

### ISSUE THREAD

**Issue by TheNaiveSamosa** [recodehive/machine-learning-repos#210]
# Brain Tumor Detection with Web App

## Description
This project aims to develop a system for detecting brain tumors using MRI images. It includes implementing deep learning models and creating a web application for easy access and usability.

### Tasks
- Implement deep learning models for brain tumor detection.
- Develop a web application interface for uploading and processing MRI images.
- Integrate the models with the web application.
- Perform testing and evaluation for accuracy and performance.
- Create documentation for usage and deployment.

Aditya Khamitkar
github.com/TheNaiveSamosa
thenaivesamosa@gmail.com
GSSoC 24' Contributor

**Comment by Ar7109** [comment]
@sanjay-kv Please assign this issue to me under GSSOC 2024
