### ISSUE TITLE
Dog Breeds Classification

### ISSUE THREAD

**Issue by vishuhere** [recodehive/machine-learning-repos#236]
🔴 Project Title: Web App for Dog Breeds Classification

🔴 Aim : Develop a user-friendly web application that allows users to upload images of dogs and receive predictions on the breed of the dog using a pre-trained machine learning model.

🔴 Approach : Create a responsive UI for image upload and result display. Set up a back-end with APIs to handle requests. Integrate a pre-trained ML model for predictions. Deploy using Docker on a cloud platform. Ensure security and monitor performance.

🔴 Participant role: GSsoC'24 Contributor 

<img width="911" alt="Screenshot 2024-06-08 at 12 47 02 PM" src="https://github.com/Recode-Hive/machine-learning-repos/assets/94856202/02463c0b-8c5f-48e8-9009-2a868585c685">
<img width="911" alt="Screenshot 2024-06-08 at 12 47 17 PM" src="https://github.com/Recode-Hive/machine-learning-repos/assets/94856202/a9b8aaed-113b-4c34-93fc-e5ee0c9a56dc">

**Comment by vishuhere** [comment]
I had already worked on this model and want to add it in your repository kindly assign me this issue under **GSsoC** label.

**Comment by Sa7yaC** [comment]
I have experience in image classification and CV , can you please assign it to me .

**Comment by vishuhere** [comment]
> I have experience in image classification and CV , can you please assign it to me .

You have to raise the issue by yourself. Watch a YouTube videos on how to contribute to open source @Sa7yaC
