### ISSUE TITLE
Adding a New Project : EMAIL SPAM CLASSIFIER

### ISSUE THREAD

**Issue by Garvanand** [recodehive/machine-learning-repos#237]
### Email Spam Classifier

This Python script utilizes machine learning techniques to classify emails as either spam or legitimate (ham). The classifier is built using logistic regression and employs the TF-IDF (Term Frequency-Inverse Document Frequency) vectorizer for feature extraction. Here's a brief overview of the workflow:

**Data Preparation:** The script loads email data from a CSV file and preprocesses it, handling missing values and converting categorical labels (spam, ham) to binary values.

**Feature Extraction:** TF-IDF vectorization is used to transform the text data into numerical features, capturing the importance of words in the documents.

**Model Training:** A logistic regression model is trained on the extracted features to learn patterns distinguishing between spam and ham emails.

**Evaluation:** The model's performance is evaluated on both training and testing datasets using accuracy metrics.

**Prediction:** Users can input an email message, and the model predicts whether it's spam or legitimate.

This classifier enables efficient identification of spam emails, contributing to a more organized and secure inbox experience.

Kindly assign it **GSSoC** label and mark it as a contribution under it

**Comment by Taranpreet10451** [comment]
Please assign this to me.

**Comment by sonali9564** [comment]
@sanjay-kv
Please assign this issue to me under GSSoC'24.

**Comment by Akanksha4554** [comment]
@sanjay-kv Please assign this issue to me under GSSoc'24.
