### ISSUE TITLE
Used Car Price Prediction Model with Web Application

### ISSUE THREAD

**Issue by ISmokeData** [recodehive/machine-learning-repos#242]
### Project : Used Car Price Prediction Model with Web Application 
In this Project, I'll use Used car details and price data set and apply Data Preprocessing, Data Visualization, Feature Selection and Multi model. I'll select those model which accuracy is good and less average error. I'll use Flask to make API and make Web Page using HTML,CSS and Javascript.

**Comment by sonali9564** [comment]
@sanjay-kv
Please assign this issue to me under GSSoC'24.

**Comment by Akanksha4554** [comment]
@sanjay-kv Please assign this issue to me under GSSoc'24.
