### ISSUE TITLE
(GSSoC'24) Adding House Price Prediction project

### ISSUE THREAD

**Issue by Apurv7777** [recodehive/machine-learning-repos#254]
### Outcomes : 
- To predict median house values in Californian districts, given a number of features from these districts.
- To understand sampling techniques like Random and Stratified.
- Visualize the Data to Gain Insights
- Looking for Correlations
- Handling Text and Categorical Attributes
- Training Linear Regression model , Decision Tree
- Evaluation Using Cross-Validation

**Comment by pavitraag** [comment]
Please assign this to me under gssoc 24

**Comment by Akanksha4554** [comment]
Dear PA,
Please assign this issue to me under GSSoc'24, I'm a contributor for GSSoC'24.
Looking forward to get assigned ASAP.

**Comment by sonali9564** [comment]
Dear PA,
Please assign this issue to me under GSSoc'24, I'm a contributor for GSSoC.
Looking forward to get assigned ASAP.

**Comment by sanjay-kv** [comment]
Its been already assigned.

**Comment by beingtony** [comment]
@sanjay-kv  will you please assign this to me . i am also GSSOC'24 contributor  and interested to work on it

**Comment by sanjay-kv** [comment]
mate Its been already assigned, please look at the assigned section, feel free to create new issues. @beingtony
