### ISSUE TITLE
Adding a new project: Airlines Delay Prediction

### ISSUE THREAD

**Issue by priyankeshh** [recodehive/machine-learning-repos#255]
# Goal

The goal of this project is to predict the delay of airlines from the given dataset.

# What will I do

- Imported all the required libraries and dataset for this project.
- Exploratory Data Analysis and Visualizing different aspects of the dataset.
- Finding number of observations and outliers in the dataset.
- Plotting different attributes of the dataset.
- Building the machine learning model.
- Finding the ost delayed Airline.

**Comment by priyankeshh** [comment]
@sanjay-kv  please assign this to me

**Comment by sonali9564** [comment]
@sanjay-kv
Please assign this issue to me under GSSoC'24.
