### ISSUE TITLE
further work on Apriori- Market Basket Analysis

### ISSUE THREAD

**Issue by poojaharihar03** [recodehive/machine-learning-repos#266]
As the folder contains a market basket analysis using the apriori algorithm. I want to further use the analysis to build a small recommendation system with which we can allow users to recommend the most relatable items. 

@sanjay-kv I would like to work on this issue as part of GSSoC. Please assign me this issue

**Comment by beingtony** [comment]
@sanjay-kv  will you please assign this to me

**Comment by sanjay-kv** [comment]
Its been already assigned, please look at the assigned section, feel free to create new issues.
