### ISSUE TITLE
AI GYM tracker 

### ISSUE THREAD

**Issue by Karansankhe** [recodehive/machine-learning-repos#276]
Automated Exercise Rep Counter is designed to enhance your workout experience by counting repetitions for you. With this innovative tool, you can focus entirely on your exercise routine without worrying about keeping track of your reps. Perfect for both gym enthusiasts and home workout practitioners, this system ensures accurate rep counting, helping you optimize your performance and achieve your fitness goals more efficiently.

**Comment by Karansankhe** [comment]
@sanjay-kv please assign me these issue

**Comment by adityasingh-0803** [comment]
@sanjay-kv i can do the task please assign me
