### ISSUE TITLE
Predictive maintainence of industrial equipment

### ISSUE THREAD

**Issue by jeet-Abhi123** [recodehive/machine-learning-repos#28]
dataset link : https://data.nasa.gov/Aerospace/CMAPSS-Jet-Engine-Simulated-Data/ff5v-kuh6/about_data
This model aims to predict industrial equipment, in this case airplane engine before failure. This dataset provides time for failure during a particular duration and predicts the remaining useful life.
The model can be made for both classification and regression.
For classification, we can make 3 conditions of the machines : i) Good condition
ii) Moderate condition
iii) Warning condition
For regression, we predict the remaining useful life for the machine.
Different models will be implement in this project.

**Comment by ldneal** [comment]
Sir Can You Assign me this project I would like to work to solve Predictive maintenance of Industrial Equipment
