### ISSUE TITLE
Web-application for movie recommendation system

### ISSUE THREAD

**Issue by nidhivmehta** [recodehive/machine-learning-repos#285]
I have enhanced the existing movie recommendation model by utilizing the Cosine Similarity algorithm after vectorizing the movie data using the "Bag of Words" technique. Additionally, I integrated this improved model into a web application using Streamlit for a more interactive user experience.

I made a web app that helps you find movies you like. It gives suggestions based on your favorite actors, genres, cast, and crews. It's all about helping you discover great movies that match your taste!

I’m a contributor for GSSoC’24; please assign me this task so that I can make a pull request.

**Comment by sanjay-kv** [comment]
Hi @nidhivmehta its not right approach to raise PR and issue together, as this is the beginner repo I approved once. until issue is assigned don't work on any Pr or raise PR
