### ISSUE TITLE
Lung Cancer Detection Using Convolutional Neural Network:

### ISSUE THREAD

**Issue by Anshika14528** [recodehive/machine-learning-repos#3]
Detection of Lung cancer utilizing Convolutional Neural Networks (CNN) with strategically designed convolutional layers, max pooling layers ,dense Layer and fully connected layers in Deep Learning.

 I agree to follow this project's Code of Conduct
 I'm a GSSoC'24 contributor
 I want to work on this issue

**Comment by sanjay-kv** [comment]
Make sure you create seperate folder and add the same

**Comment by itssiddhantjain** [comment]
Hello @sanjay-kv , please assign this issue to me as I have already worked on this kind of problem in the past.
