### ISSUE TITLE
 NYC Taxi Trip Duration Prediction

### ISSUE THREAD

**Issue by bristiHalder** [recodehive/machine-learning-repos#310]
- Objective: Predict the duration of taxi trips in NYC accurately.

- Data: Utilize a dataset containing information such as pickup/dropoff locations, timestamps, distance, and passenger count.

- Modeling: Implement regression techniques such as Multiple Linear Regression, Decision Trees, Random Forests, and Gradient Boosting to train predictive models.

- Evaluation: Assess model performance using metrics like Mean Squared Error (MSE) and Root Mean Squared Error (RMSE).

**Comment by anushkasaxena07** [comment]
@sanjay-kv please assign this issue to me
