### ISSUE TITLE
leaderboard 

### ISSUE THREAD

**Issue by AKSHITHA-CHILUKA** [recodehive/machine-learning-repos#311]
Create evaluate.py https://github.com/Recode-Hive/machine-learning-repos/pull/303
Create train.py https://github.com/Recode-Hive/machine-learning-repos/pull/295
Create plant-disease-detection https://github.com/Recode-Hive/machine-learning-repos/pull/278
Update README.md https://github.com/Recode-Hive/machine-learning-repos/pull/279
Create data_preprocessing.py https://github.com/Recode-Hive/machine-learning-repos/pull/280
Plant Disease Detection using CNN https://github.com/Recode-Hive/machine-learning-repos/issues/134
these are my PR links which are merged and these are not getting updated to leaderboard

**Comment by sanjay-kv** [comment]
![image](https://github.com/Recode-Hive/machine-learning-repos/assets/30715153/32e4cc44-28ba-4ca7-88ce-b8687d9ef706)


few of them is under review, once finished it will be updated, remaining I can see it on the leaderboard.
