### ISSUE TITLE
Pokemon Recommendation and Classification System with web application

### ISSUE THREAD

**Issue by RajKhanke** [recodehive/machine-learning-repos#363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

there will be two features in web application of this project 
1)Pokémon classification System
- classify  different Pokémon based  on images
2)Pokémon recommendation System
- recommends Pokémon using collaborative filtering based on provided  input features by user

along with this i will provided a complete analysis on data in notebook with EDA and readme.md file for reference.

### Use Case

In this real world, there are many child enthusiasts who are watching Pokemon, they may be excited to see which Pokemon have what features so  by inputting features like attack level, defense level, height ,width, type etc , this features recommends different pokemons along with images for them making the experience more exciting. 

### Benefits

The project has following benefits :-
1)using ML and DL making a system that create enthusiasm in children
2)classifying different  Pokémon making it easier for  Pokémon lovers, which Pokémon has what body structure
3)using Pokémon Recommendation system, it becomes easier for Pokémon lovers to  judge Pokémon's based on their features.

### Add ScreenShots

none

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RajKhanke** [comment]
@sanjay-kv please assign this to me with label and level

**Comment by sanjay-kv** [comment]
I hope you know the limitation on this repos.
