### ISSUE TITLE
💡[Feature]: Restaurant Recommender

### ISSUE THREAD

**Issue by pavitraag** [recodehive/machine-learning-repos#387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This recommender is used for recommending the nearest restaurants given the location of user.

### Use Case

Finding nearby restaurants .

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by malvika-sinha** [comment]
I wish to work on this. kindly assign this task to me.

**Comment by Kirti-Pant** [comment]
I can work on this project , kindly assign this task to me.
