### ISSUE TITLE
Add machine learning Resources 

### ISSUE THREAD

**Issue by aslams2020** [recodehive/machine-learning-repos#400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

To provide valuable information and support for users interested in machine learning, I want to add additional resources to the following sections -
- Additional Courses for ML
- Additional resources for interview 
- Additional YouTube Channel resources
- Additional ML datasets

### Suggested Change

Want to add additional resources to the above mentioned sections.

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
whats the ml resource you planning to add
