### ISSUE TITLE
💡[Feature]: Add brain tumor classification using CNN

### ISSUE THREAD

**Issue by debangi29** [recodehive/machine-learning-repos#408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

We have brain tumor detection but not brain tumor classification
So, can add ML model to divide brain tumor into its 4 types using CNN

### Use Case

We have brain tumor detection but not brain tumor classification
So, can add ML model to divide brain tumor into its 4 types using CNN 
It will be easy to cure if we know the brain tumor type

### Benefits

It will be easy to cure if we know the brain tumor type

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by CodeSage4** [comment]
hello @sanjay-kv  please assign this to me
