### ISSUE TITLE
Email Spam Detection Using Machine Learning

### ISSUE THREAD

**Issue by SurajSanap** [recodehive/machine-learning-repos#44]
The objective of this project is to develop a machine learning model capable of detecting spam emails. With the increasing volume of email communication, distinguishing between spam and legitimate emails has become crucial. Effective spam detection can enhance email security and improve user experience by reducing unwanted and potentially harmful emails.

**Comment by SurajSanap** [comment]
Please assign me this issue

**Comment by SurajSanap** [comment]
Issue solved #43

**Comment by itssiddhantjain** [comment]
Hello @sanjay-kv , please assign this issue to me as I have already worked on this kind of problem in the past.

**Comment by Pranali3103** [comment]
Hello @sanjay-kv please assign this issue to me.

**Comment by sanjay-kv** [comment]
Issue will be assigned to Only 1 person ...FCFS basis. 
Others get a chance if the issue gets stale & the assignee is inactive for 5+ days
Also if you would like to work on more issue create a new issue and I will create label and assign you.

Feel free to create new issue, I will assign to you
