### ISSUE TITLE
Movie Recommendation system using machine learning

### ISSUE THREAD

**Issue by Harshita297** [recodehive/machine-learning-repos#46]
Recommends 5 movies based on genres of the movie.
Kindly assign this task to me under gssoc'24
Thank you

**Comment by itssiddhantjain** [comment]
Hello @sanjay-kv , please assign this issue to me as I have already worked on this kind of problem in the past.

**Comment by aryanchauh** [comment]
Hello @sanjay-kv sir !
Can you please assign me this issue I wanna fix this issue under GSSOC24

**Comment by Manyata-Patra** [comment]
Hello Sir!
Can you please assign me this issue.I have previous knowledge on this and I have worked on this project.

**Comment by SayantikaLaskar** [comment]
I would like to work on this issue kindly assign me this issue
