### ISSUE TITLE
💡[Feature]: K-means clustering to group customers based on their purchase history

### ISSUE THREAD

**Issue by Amishachoudhary22** [recodehive/machine-learning-repos#490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Create a K-means clustering algorithm to group customers of a retail store based on their purchase history.

### Use Case

A retail store wants to understand their customer base better to develop targeted marketing campaigns and improve customer satisfaction. They have a dataset containing customer purchase history, including information like:

Customer ID
Transaction date
Amount spent
Items purchased (optional)
By applying K-means clustering to this data, the store can segment customers into groups with similar buying behaviors. This helps them create targeted marketing campaigns for each segment.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by honey7733** [comment]
I would like to work on this project. Please assign it to me.
