### ISSUE TITLE
Music Genre Detection using Machine Learning Models

### ISSUE THREAD

**Issue by ughrima** [recodehive/machine-learning-repos#51]
This project will delve into the factors contributing to the classification of music genres and develop a predictive model to accurately identify the genre of a given piece of music.

I agree to follow this project's Code of Conduct.
I'm a GSSoC'24 contributor.
I want to work on this issue.

**Comment by aryanchauh** [comment]
Can you assign me this project? @sanjay-kv  I have done work on this project before
