### ISSUE TITLE
analysis of titanic train dataset

### ISSUE THREAD

**Issue by anushkasaxena07** [recodehive/machine-learning-repos#532]
@sanjay-kv plz assign this issue to me

**Comment by sanjay-kv** [comment]
i know its the kaggle dataset, try not just replicate the same

**Comment by anushkasaxena07** [comment]
@sanjay-kv so i can not use that dataset ?

**Comment by sanjay-kv** [comment]
you can use. but no copy paste code.

**Comment by anushkasaxena07** [comment]
ok
