### ISSUE TITLE
💡[Feature]: Fruit and Vegetable Disease detection (healthy or rotten)

### ISSUE THREAD

**Issue by Rukkya** [recodehive/machine-learning-repos#541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

developing initially a web application that uses the camera to capture images of fruit or vegetables and tell if it's healthy or rotten using computer vision and deep learning models.

### Use Case

it will help automation in fruit markets or juice factories for example, the machine would be able to recognize rotten fruits and remove it which in case will enhance production pipeline

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Rukkya** [comment]
hello @sanjay-kv plz assign this issue to me

**Comment by Shantnu-singh** [comment]
Hey @sanjay-kv, I've been working on ML models for a long time and this is my first time contributing to GGSOC. I believe I can be a great help to you.
