### ISSUE TITLE
Addition of apt documentation and readme file

### ISSUE THREAD

**Issue by kc-m13** [recodehive/machine-learning-repos#60]
The repository lacks a proper documentation of the projects plus a systematic beginner friendly readme guiding the newbies as to how they're supposed to start. I wish to add the same along with a short vid tutorial.

I wish to work on this issue.
I will follow the proper code of conduct of GSSOC 2024.
I am a GSSOC 2024 contributor.

**Comment by sanjay-kv** [comment]
Hi, i got busy with leaderboard launch, assigned this issue to you
