### ISSUE TITLE
💡[Feature]: NetFlix Stock Price Prediction System

### ISSUE THREAD

**Issue by ashis2004** [recodehive/machine-learning-repos#607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Predicting stock prices is an important application of machine learning in finance. we will use machine learning algorithms to predict the stock prices of Netflix, one of the leading companies in the entertainment industry.
We will use historical stock price data for Netflix to train and test machine learning models. The data consists of the following columns:

Date: The date of the stock price

Open: The opening price of the stock on that day

High: The highest price of the stock on that day

Low: The lowest price of the stock on that day

Close: The closing price of the stock on that day

### Use Case

Investment Strategies: Investors can use the prediction system to develop and refine their investment strategies. By anticipating future stock price movements, they can make more informed decisions about when to buy or sell Netflix shares.

Risk Management: Financial analysts and portfolio managers can utilize the system to assess the risk associated with holding Netflix stock. Accurate predictions can help in diversifying portfolios and mitigating potential losses.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by CodeSage4** [comment]
hey @sanjay-kv please assign this issue to me i have experience with predictive analytics and time series data

**Comment by ashis2004** [comment]
@CodeSage4 I'm already doing

**Comment by CodeSage4** [comment]
okay if you need any help ask me!
