### ISSUE TITLE
Adding Credit Card Fraud Detection 

### ISSUE THREAD

**Issue by bristiHalder** [recodehive/machine-learning-repos#61]
For this project, I will be using Logistic Regression model.
It will involve classifying transactions as either fraudulent or legitimate. This method leverages a statistical model to estimate the probability of fraud based on various transaction features, such as amount, time, and user behavior.

**Comment by Manyata-Patra** [comment]
Hello sir, can you please assign me this issue as I have already made a project on this before.

**Comment by sanjay-kv** [comment]
Hi, i got busy with leaderboard launch, assigned this issue to you

**Comment by PadmalathaKasireddy** [comment]
Hello, @sanjay-kv 
I am intrested in contributing to this issue, please assign me to this issue.
Thank you.
