### ISSUE TITLE
New Project : Colorization of Images

### ISSUE THREAD

**Issue by Royal-Emine** [recodehive/machine-learning-repos#64]
![image](https://github.com/Recode-Hive/machine-learning-repos/assets/112507451/58623e5a-184e-4589-9f36-a4e955136c94)
 

It looks somewhat like this while the code (Python) is implemented. It is a new project suggested to be included in the repository to improve the quality. It can provide better colour to B/W images or degraded pictures.

**Comment by sanjay-kv** [comment]
Hi, i got busy with leaderboard launch, assigned this issue to you
