### ISSUE TITLE
💡[Feature]: Sign Language Detection

### ISSUE THREAD

**Issue by ShraddhaSabde** [recodehive/machine-learning-repos#653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Sign language is manual communication commonly used by people who are deaf. Sign language is not universal; people who are deaf from different countries speak different sign languages. The gestures or symbols in sign language are organized in a linguistic way. Each individual gesture is called a sign. Each sign has three distinct parts: the handshape, the position of the hands, and the movement of the hands.

### Use Case

-

### Benefits

1. Sign language translator AI .

2. Hand Talk Translator .

### Add ScreenShots

![sign1](https://github.com/user-attachments/assets/92d512b7-28eb-4bb1-86aa-8d0997a39240)
![sign2](https://github.com/user-attachments/assets/d7a9680b-37ea-41f4-b151-1001c3f4f8a0)
![sign4](https://github.com/user-attachments/assets/0763e18c-68e1-47c0-962d-c707890a1857)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ShraddhaSabde** [comment]
Sir I have a doubt you have assigned label to this pull request and due to large file size not merged it.
So will the label come in leaderboard or not because it is not showing in leaderboard?

**Comment by sanjay-kv** [comment]
no this wont come, you can make the change in the PR and send PR again I will merge it/
Only merged PR counts

**Comment by ShraddhaSabde** [comment]
ok sir
