### ISSUE TITLE
Face Recognition with Attribute Analysis

### ISSUE THREAD

**Issue by Royal-Emine** [recodehive/machine-learning-repos#66]
The proposal is solely based on the project where various constraints are implemented to analyze a facial structure and display an analysed report. The project is aimed to be subjected in the Machine Learning and Data Science / Intermediate or Advanced folder.

![image](https://github.com/Recode-Hive/machine-learning-repos/assets/112507451/39d8ed4f-84da-4ae2-abbe-2c7dee008b79)

It detects age, gender, facial expression (including angry, fear, neutral, sad, disgust, happy and surprise) and race (including asian, white, middle eastern, indian, latino and black) predictions. Result is going to be the size of faces appearing in the source image.

**Comment by Diyaa0313** [comment]
I want to work on this issue please assign it to me

**Comment by sanjay-kv** [comment]
Hi, i got busy with leaderboard launch, assigned this issue to you

**Comment by Diyaa0313** [comment]
@sanjay-kv I completed a detailed analysis on age, gender and ethnicity using a dataset from kaggle. However, I did not get any which included emotions as well. Can you please provide a dataset link  which includes all four?
