### ISSUE TITLE
💡[Feature]: New Website to handle all the projects

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/machine-learning-repos#663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

@partha120804 Hi right now when you look into the repo, people created random folders, this might help for people who just do code search. but for a wider audience who is new to data science, this might be hard, they might want to see how the thing is working and all. 

So the requirement is not big, you can copy the code base from the other repository we just making the existing contribution to reach wider people on internet. 

### Use Case

![image](https://github.com/user-attachments/assets/208cdff0-88fa-48fe-8ebb-4e1668196152)

Sample you can refer: 
https://github.com/HimanshuNarware/Devlabs
https://github.com/CodeHarborHub/codeharborhub.github.io
https://github.com/jfmartinz/ResourceHub
@partha120804 

### Benefits

✅Easy to understand how the project works and redirect to GitHub.

### Add ScreenShots

Watch this Video: https://www.loom.com/share/5eb7d4e5851d4ca087a8ad788caaeb43?sid=1f94b15c-03a1-40a7-a7ec-a3cdcb163541

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by partha120804** [comment]
what i have to do ??

**Comment by sanjay-kv** [comment]
I will mention in details soon.

**Comment by partha120804** [comment]
ok

**Comment by sanjay-kv** [comment]
You can check the details above @partha120804

**Comment by sanjay-kv** [comment]
@partha120804 are you working on it?

**Comment by partha120804** [comment]
> @partha120804 are you working on it?

Yes

**Comment by sanjay-kv** [comment]
can i know how long days you need to complete this, so I can plan the promotion accordingly. Thanks

**Comment by partha120804** [comment]
@sanjay-kv I have little bit experience and have worked with frontend and designing stuff, this website will require backend to handle all the subfolders, I think assigning someone skilled in backend will be a good idea to this project. I can help him with the UI/UX but creating the page from scratch can be a bit challenging for me. 

Can I work with someone else on this project ?

**Comment by sanjay-kv** [comment]
No worries
