### ISSUE TITLE
ADD-Crop Classification and Recommendation

### ISSUE THREAD

**Issue by saikrishna823** [recodehive/machine-learning-repos#70]
I want to add this project to this repository.This problem statement is basically a multiclassification problem statement.I will use different ml algorithms like Naivebyes,RandomForest,Xgboost,Decisiontrees.I will also deploy it in streamlit too.

**Comment by saikrishna823** [comment]
KIndly assign this issue to me

**Comment by sanjay-kv** [comment]
Hi, i got busy with leaderboard launch, assigned this issue to you
