### ISSUE TITLE
Customer Segmentation Using Clustering(NOT the Usual K-means One)

### ISSUE THREAD

**Issue by SkSadaf** [recodehive/machine-learning-repos#72]
In the project the Customer Segmentation is done using a combination of three algorithms ( DBSCAN, Hierarchical and K-means),
The user can input the dataset and get the output in the form of graphs and can also download the csv files of individual clusters, Additionally Shilloute scores have been displayed to understand the efficiency of the clusters. I want to add this project to your repo as this would be a great application of machine learning that would help learners understand the practical applications. Please assign this to me under GSSOC'24. Thank you.

**Comment by Diyaa0313** [comment]
please assign me this issue @SkSadaf

**Comment by sanjay-kv** [comment]
Hi, i got busy with leaderboard launch, assigned this issue to you

**Comment by SkSadaf** [comment]
Thanks for assigning the issue, I am working on it.
