### ISSUE TITLE
Data Clustering:  K-Means algorithm to cluster a dataset using Sckit-learn 

### ISSUE THREAD

**Issue by akashlogics** [recodehive/machine-learning-repos#76]
Clustering:
K-Means Clustering:
       A simple example that demonstrates how to use the K-Means algorithm to cluster a dataset into different groups. To demonstrate K-Means Clustering using Scikit-learn, The generated dataset is visualized before and after clustering, showing the cluster assignments and cluster centers.

I am well-known in this topic can you please assign me this issue.

please label it GSsoc 24

**Comment by TanishaVerma-08** [comment]
Hello there, I am a GSSoc'24 contributor. Being a Machine learning student, I have been working on different algorithms like K-means clustering, SVM, Decision Trees. I have done some good research about this topic. 
Kindly assign me the issue.

**Comment by akashlogics** [comment]
@TanishaVerma-08 I have already completed the issue and waiting for the admin to assign me

**Comment by sanjay-kv** [comment]
Hi, i got busy with leaderboard launch, assigned this issue to you

**Comment by akashlogics** [comment]
thank you for assigning me the issue
