### ISSUE TITLE
Face verification using Deep learning

### ISSUE THREAD

**Issue by Aditijainnn** [recodehive/machine-learning-repos#766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The face Recognition is done using Facenet model. Used a pretrained facenet model to compare the captured image with images in database to verify person's face

### Use Case

Live Face Verification Using Deep Learning

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
I will assign few level3 so you can reach max of 150 points. then will remove 4 points from gg extn as you cross the limit
[Uploading screencapture-life-made-easy-vercel-app-2024-07-17-09_56_54.pdf…]()

**Comment by Aditijainnn** [comment]
But from gg extension i scrored around 190 points only
