### ISSUE TITLE
Sentimental analysis on a women's clothing database using NLTK

### ISSUE THREAD

**Issue by ManasiDhotkar** [recodehive/machine-learning-repos#78]
So in these project, a sentiment-based dataset related to women's clothing typically consists of textual data such as reviews, comments, or product descriptions, along with corresponding sentiment labels indicating whether the sentiment expressed in each text is positive, negative, or neutral.

**Comment by sanjay-kv** [comment]
Hi, i got busy with leaderboard launch, assigned this issue to you

**Comment by ananyabansal16** [comment]
I can help with this issue,you can assign it to me under GSSoC'24.

**Comment by Samik123Mit** [comment]
pls assign me the issue,i will make sure the task is done,I have prior experience with the model too.

**Comment by Yogesh-ok55** [comment]
please assign this issue to me
