### ISSUE TITLE
💡[Feature]: Vehicle Lane Detection Using Machine Learning and OpenCV

### ISSUE THREAD

**Issue by aviralgarg05** [recodehive/machine-learning-repos#792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Detect vehicle lanes using opencv and machine learning

### Use Case

Can be used in cctv cameras and observation purposes

### Benefits

Beneficial in preventing accidents, collecting datasets for driver mindset etc.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ankitaa-a** [comment]
@sanjay-kv  I would like to work on this can you assign this to me?
