### ISSUE TITLE
💡[Feature]: Stair Cases Segmentation using Deep Learning

### ISSUE THREAD

**Issue by sreevidya-16** [recodehive/machine-learning-repos#796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to develop a Deep Learning Based Stair Segmentation and Behavioral Cloning for Autonomous Stair Climbing

I got this idea by reading this [research paper](https://www.worldscientific.com/doi/abs/10.1142/S1793351X1940021X)

I want to implement this using PyTorch and Fast.ai library
@sanjay-kv, could you please assign me this issue under GSSOC'24

### Use Case

Mobile robots are widely used in the surveillance industry, for military and industrial applications. In order to carry out surveillance tasks like urban search and rescue operation, the ability to traverse stairs is of immense significance. 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
![image](https://github.com/user-attachments/assets/2e84e4db-441e-4670-b950-bfd747eb1557)
you already gor 150 max point from this repo so i will be closing this issue
