### ISSUE TITLE
💡[Feature]: Body Fat Prediction

### ISSUE THREAD

**Issue by Khushi-Pushkar** [recodehive/machine-learning-repos#798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Body Fat Prediction is the process of estimating an individual's body fat percentage using machine learning techniques. Accurate body fat estimation is crucial for assessing health and fitness levels, managing weight, and preventing obesity-related diseases.

### Use Case

Dataset : https://www.kaggle.com/datasets/fedesoriano/body-fat-prediction-dataset

### Benefits

Helps in early detection of obesity-related health issues like diabetes, cardiovascular diseases, and metabolic syndrome.

Provides data to support public health policies aimed at reducing obesity rates and promoting healthy lifestyles.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
![image](https://github.com/user-attachments/assets/947a8d10-7e76-4d65-ae9d-ece77c7682e7)
![image](https://github.com/user-attachments/assets/38e5ab3e-0590-4cbf-b106-5dff54d919f3)

I found there is more documentation did here, will be removing the same.
