### ISSUE TITLE
💡[Feature]: Add Pima Indians Diabetes Database Prediciton

### ISSUE THREAD

**Issue by vivekvardhan2810** [recodehive/machine-learning-repos#808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will predict the Pima Indians Diabetes Database (Predict the onset of diabetes based on diagnostic measures) using LSTM, KNN, K Means Clustering, SVM.  The objective of the dataset is to diagnostically predict whether or not a patient has diabetes, based on certain diagnostic measurements included in the dataset. Several constraints were placed on the selection of these instances from a larger database.

### Use Case

Socio-Economic Factor

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
this will be the last documentation work, you will be reaching 150 points after this

**Comment by vivekvardhan2810** [comment]
Okay Sir
