### ISSUE TITLE
ADD-Heart Disease Prediction

### ISSUE THREAD

**Issue by saikrishna823** [recodehive/machine-learning-repos#82]
I want to build a model that can predict whether a person has heart disease or not.I have experience in working with various ML algorithms and also build projects in this domain too.

**Comment by saikrishna823** [comment]
Please assign this issue to me.

**Comment by TanishaVerma-08** [comment]
Hello there, I am a GSSoc'24 Contributor. I have been working on a project related to heart disease detection and would like to contribute it here. KIndly assign me the issue

**Comment by Jatin9826** [comment]
Hello there, I am a GSSoc'24 Contributor. I have been working on a project related to heart disease detection and would like to contribute it here. KIndly assign me the issue

**Comment by SayantikaLaskar** [comment]
I would like to work on this issue kindly assign me this issue
