### ISSUE TITLE
💡[Feature]: Face Mask Detection

### ISSUE THREAD

**Issue by ShraddhaSabde** [recodehive/machine-learning-repos#839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Face mask detection using machine learning has several important applications-
Public Health and Safety, Automated Monitoring, Access Control.
The model uses Convolutional Neural Network. 

### Use Case

-

### Benefits

-

### Add ScreenShots

-

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kumar8074** [comment]
@sanjay-kv can you please assign me this issue
