### ISSUE TITLE
Add Linear Regression Model 

### ISSUE THREAD

**Issue by Aditi22Bansal** [recodehive/machine-learning-repos#86]
This has been made in Kaggle using dataset and has ML

**Comment by Aditi22Bansal** [comment]
@sanjay-kv 
Kindly assign me this 
Thankyou

**Comment by PadmalathaKasireddy** [comment]
@sanjay-kv 
I am intrested in contributing to this project. Please assign me to this issue.
Thank you.

**Comment by Samik123Mit** [comment]
pls assign me the issue,i will make sure the task is done,I have prior experience with the model too.

**Comment by Devanik21** [comment]
please ,I am interested in contributing to this project. Kindly,assign me  this issue.
Thank you.
