### ISSUE TITLE
💡[Feature]: Chronic Kidney Disease Prediction

### ISSUE THREAD

**Issue by bristiHalder** [recodehive/machine-learning-repos#867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This work aims to accurately predict Chronic Kidney Disease (CKD) using a robust Artificial Neural Network model. It compares its performance to various machine learning algorithms, ultimately achieving an impressive accuracy of 98%, making it a promising tool for CKD diagnosis.

### Use Case

Advancing the accuracy of Chronic Kidney Disease (CKD) prediction is crucial due to its widespread impact and severe consequences. Globally, CKD affects approximately 10% of the population, yet a staggering 90% of cases remain undiagnosed until reaching advanced stages. By improving predictive models, we can detect CKD earlier, potentially reducing complications and improving patient outcomes.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
there is already similar one in the repo
