### ISSUE TITLE
Movie Recommendation System

### ISSUE THREAD

**Issue by Srijansarkar17** [recodehive/machine-learning-repos#92]
The project of Movie Recommendation is an interesting one.
It will machine learning techniques like cosine similarity for prediction and recommendation of movies according to the user's search.
I have worked on this type of project before.
I would like you to please assign me this project!!

**Comment by Tanmaymathur03** [comment]
I have created a robust Movie Recommendation System using normalized preprocessing and of course vectorizing the similarities. I could be a perfect fit for this issue, hope you grant me access as i have participated in GSOC.

**Comment by sanjay-kv** [comment]
Hi, i got busy with leaderboard launch, assigned this issue to you

**Comment by Srijansarkar17** [comment]
> Hi, i got busy with leaderboard launch, assigned this issue to

**Comment by Srijansarkar17** [comment]
> Hi, i got busy with leaderboard launch, assigned this issue to you

Hey thanks for assigning me the issue. I have sent you a PR request. Can you please look into it?
