### ISSUE TITLE
Price of House price prediction

### ISSUE THREAD

**Issue by sd-coder07** [recodehive/machine-learning-repos#949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Feature Description
1. Location (Latitude and Longitude):

Description: The geographical coordinates of the property.
Role in Prediction: Essential for capturing the neighborhood characteristics and proximity to amenities, which significantly impact house prices.
2. Number of Bedrooms:

Description: The total number of bedrooms in the property.
Role in Prediction: Directly correlates with the size and suitability of the house for families, affecting its market value.
3. Number of Bathrooms:

Description: The total number of bathrooms.
Role in Prediction: More bathrooms typically increase the convenience and appeal of the property, impacting its price.
4. Square Footage:

Description: The total area of the house in square feet.
Role in Prediction: Larger homes generally have higher values, making this a critical feature for prediction.
5. Lot Size:

Description: The size of the property’s lot in square feet or acres.
Role in Prediction: Larger lots can add significant value, especially in suburban or rural areas.

### Use Case

Use Case

Real Estate Agencies and Brokers:
Description: Real estate professionals can use house price prediction models to provide accurate pricing recommendations for buyers and sellers.
Impact: Helps in setting competitive prices, attracting buyers, and ensuring sellers get the best value for their property.

Home Buyers:
Description: Potential buyers can use prediction tools to assess whether the asking price of a property is fair.
Impact: Enables buyers to make informed decisions and potentially negotiate better deals.

Home Sellers:
Description: Sellers can determine the optimal listing price for their properties.
Impact: Helps in selling the property faster and at a fair market value.

Mortgage Lenders:
Description: Lenders can use prediction models to assess the value of a property for mortgage approval.
Impact: Reduces the risk of lending and ensures loans are backed by adequately valued assets.

### Benefits

Benefits
1. Accurate Valuation:

Benefit: Provides precise and data-driven property valuations.
Impact: Reduces the risk of overpricing or underpricing properties.
2. Market Insights:

Benefit: Offers insights into market trends and property value drivers.
Impact: Helps stakeholders understand the real estate market dynamics.
3. Enhanced Decision-Making:

Benefit: Supports informed decision-making for buyers, sellers, and investors.
Impact: Leads to better financial outcomes and satisfaction among stakeholders.
4. Time Efficiency:

Benefit: Automates the valuation process, saving time for real estate professionals and clients.
Impact: Speeds up transactions and reduces the time properties spend on the market.
5. Risk Management:

Benefit: Helps lenders and investors manage risks by ensuring properties are accurately valued.
Impact: Minimizes financial losses and enhances portfolio stability.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
this is already done
