### ISSUE TITLE
T20 World Cup target score Prediction

### ISSUE THREAD

**Issue by avii-07** [recodehive/machine-learning-repos#97]
Hello @sanjay-kv ,
Sir, I am Avi Mittal, one of the contributors under GSSOC'24. 

I will make a machine learning model to predict the target score after the 1st innings of the T20 cricket match. I have experience making machine-learning models and have worked in this domain also.

I request you to please assign me this project.

**Comment by avii-07** [comment]
@sanjay-kv sir,

I am trying to clone the forked repository but I am unable to clone it. Please help me.

**Comment by sanjay-kv** [comment]
give me something like error message, screenshot. 
what code you enter. 
link to fork repo.

**Comment by avii-07** [comment]
This is the error I am getting. I tried to clone the repository using desktop github as well but getting the same error.

**Comment by avii-07** [comment]
@sanjay-kv 

Yes Sir, I was able to clone the repository successfully in command prompt. 
I have also created the PR. Kindly review it.

Thank you..

**Comment by sanjay-kv** [comment]
okay
